### ISSUE TITLE
Can ASINetworkQueue get a NSDictionary "userInfo" ?

### ISSUE THREAD

**Issue by leviathan** [pokeb/asi-http-request#10]
In order to distinguish between multiple queues it would be great if ASINetworkQueue gets a "userInfo" NSDictionary.

I've already added it to this gist source here: http://gist.github.com/215015

**Comment by pokeb** [comment]
Hi again

Can you explain more about when you might need to be able to do this? In general you should avoid having several queues in use at the same time, if requests are running in each it will degrade performance and increase the chances that requests will timeout.

Perhaps you'd like to use a feature like this in some other way, if I can understand more about why you want this, it will help. :)

Best

Ben

**Comment by leviathan** [comment]
Actually I don't run multiple queues at the same time. Its always one after the other. 

But, when a queue is finished I want to broadcast some events. Therefore I need some information about the resources this queue and its request have been working on.

In my case I mark a "container" for download. This container has information about resources, which should be downloaded. So I create a queue for this container and add multiple request for the single downloads. I start the queue and when its finished I want to trigger some events to let the application know that the resources (a.k.a. container) are now available locally.

I figured that having a NSDictionary 'userInfo' for storing this kind of information with the queue would be a good thing.

**Comment by pokeb** [comment]
Ok, cool. I'll add this in the next couple of days.

Alternatively, if you create an ASIHTTPRequest fork on GitHub (it's really easy if you haven't done it before) and publish this change there, I can merge it in easily and you'll be credited as the author directly in the commit.

Thanks

Ben

**Comment by leviathan** [comment]
Hi Ben,

I've forked your project and added the NSDictionary "userInfo" addition to ASINetworkQueue. Please find the fork here: http://github.com/mobilemelting/asi-http-request

**Comment by leviathan** [comment]
Do I need to do anything else or can you simple merge this into your trunk?

**Comment by pokeb** [comment]
Great, thanks very much! I'll merge it in later this week.

One small issue - the dictionary needs to be a retained property.

Best,

Ben

**Comment by leviathan** [comment]
Fixed that and commited to the branch.

**Comment by pokeb** [comment]
Ok, it's in master now.
