### ISSUE TITLE
Handling of HTTP responses together with download cache is weird

### ISSUE THREAD

**Issue by 0xced** [pokeb/asi-http-request#100]
Two things are bothering me the way HTTP responses and cache are handled together.
1. The `request:didReceiveResponseHeaders:` message is not sent to the delegate when the data is retrieved from cache, even if a 304 response is received. At https://github.com/pokeb/asi-http-request/blob/v1.8/Classes/ASIHTTPRequest.m#L2062 the method `readResponseHeaders` returns without sending the `request:didReceiveResponseHeaders:` message to its delegate.
2. At https://github.com/pokeb/asi-http-request/blob/v1.8/Classes/ASIHTTPRequest.m#L3299 the response code is set to 200, even if it was actually a 304 response code.

**Comment by pokeb** [comment]
Hi Cédric

Sorry for the delay in getting back to you on this!

On the second point, IIRC it originally preserved the status code it got back, but people complained that it wasn't what they wanted, so I changed it to always be 200 if the response was pulled from the cache. I agree this should be documented though... :)

On the first point, I see what you mean, I just wonder how useful this would be. If you feel strongly that it should change, I'm happy to change it, but it would be helpful to know how you're using this for cached responses.

Best

Ben

**Comment by mhkhung** [comment]
I set the cache policy to 
        [request setCachePolicy:ASIAskServerIfModifiedCachePolicy|ASIFallbackToCacheIfLoadFailsCachePolicy];

Why is it that data is returned from the cache even the server's responding 200? I saw the server responded 200 with new data but the data is still pulled from the cache..
