### ISSUE TITLE
Deadlock bug in ASIDownloadCache.m 

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [pokeb/asi-http-request#102]
In version 1.8.....
Line 318, return point needs [[self accessLock] unlock];

Without this there is a deadlock when connecting to a server that doesn't have explicit cache expiration time.

**Comment by pokeb** [comment]
Fix deadlock in ASIDownloadCache when server doesn&#39;t return any explicit expiration time
Closed by 6d0aa0baa5473e4aa7a83fe4290b195f83ddf3b9 (Many thanks to LeeMatthewHiggins for catching this)
