### ISSUE TITLE
Use of [NSFileManager defaultManager] in HttpRequest is not threadsafe

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [pokeb/asi-http-request#105]
Apple docs state that [NSFileManager defaultManager] singleton is not thread safe on iOS.
Its use in handleStreamComplete could be a problem when streaming many files direct to file system (rare but there). Fix would be to alloc instance instead (which apple states is threadsafe).

**Comment by pokeb** [comment]
Stop using NSFileManager&#39;s defaultManager (closed by 8245ca547a99223d743776a9cd5cde4a029fcc8b)

**Comment by pokeb** [comment]
Should be fixed now, many thanks for pointing this out! :)
