### ISSUE TITLE
DownloadCache: "Max-age" should override "Expires"

### ISSUE THREAD

**Issue by antonholmquist** [pokeb/asi-http-request#108]
14.9.3. "... If a response includes both an Expires header and a max-age directive, the max-age directive overrides the Expires header, even if the Expires header is more restrictive."
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

The method "isCachedDataCurrentForRequest:" in DownloadCache clearly checks for the Expires directive first if shouldRespectCacheControlHeaders=YES.

**Comment by pokeb** [comment]
ASIDownloadCache: If we get a max-age, ignore any Expires header
closed by e357f3ca7c11dbe258cd25813941d9aad5b12681

**Comment by pokeb** [comment]
Many thanks :)
