### ISSUE TITLE
ASIDownloadCache: isCachedDataCurrentForRequest breaks on "public, max-age=1000"

### ISSUE THREAD

**Issue by antonholmquist** [pokeb/asi-http-request#109]
The scanner in isCachedDataCurrentForRequest: assumes that the cache directive begins with "max-age" and breaks on "public, max-age=x.".

This can be fixed by adding the line:
[scanner scanUpToString:@"max-age" intoString:NULL];

Code with new line added:

// Look for a max-age header
        NSString *cacheControl = [[cachedHeaders objectForKey:@"Cache-Control"] lowercaseString];
        if (cacheControl) {
            NSScanner *scanner = [NSScanner scannerWithString:cacheControl];
            [scanner scanUpToString:@"max-age" intoString:NULL];
            if ([scanner scanString:@"max-age" intoString:NULL]) {

**Comment by pokeb** [comment]
Fix cache-control max-age header parsing
Closed by b6663aaaf7819a6ae93a84307788ac59abe77e42

**Comment by pokeb** [comment]
Thanks again! :)
