### ISSUE TITLE
NSDate, memory building up

### ISSUE THREAD

**Issue by JanWillemDeBirk** [pokeb/asi-http-request#110]
I'm using ASIHTTP for the iPad (v1.8-14 2010-12-02).

On several occasions in the framework, but especially in the ASIHTTPRequest.m, line 3051, [NSDate date] is used.

For some reason, this causes memory consumption to build up (quite a lot), and only releases the NSDates after the download has completed (or failed).

At some point, there are more than 18.000 objects alive (depending on the download size, but our download is a zip file that ranges from 100 MB to 500 MB).

It appears to be that an autorelease pool is out of place. I didn't want to dive into the code too deep, so I decided to file a bug.

**Comment by pokeb** [comment]
Hi Jan

I've added an autorelease pool around the network event handler, which seems to fix this. I have a feeling this used to be there, but I took it out, mistakenly assuming the runloop would drain the pool for us after the callback had run.

Anyhow, it would be great if you could update your copy of ASIHTTPRequest, and let me know if this solves the issue.

Best

Ben

**Comment by JanWillemDeBirk** [comment]
Hi Ben,

Thank you for your swift reply. Your fix works like a charm (didn't do a full update, but merged the fix in ASIHTTPRequest.m myself). NSDate went from 18k objects to just 10 and memory is stable again.

I can also confirm that the autorelease pool used to be there in previous version of the framework.

Again, thank you.
