### ISSUE TITLE
Bug in ASIDataCompressor and ASIDataDecompressor

### ISSUE THREAD

**Issue by 0xced** [pokeb/asi-http-request#113]
See [Lighthouse #69](http://allseeing-i.lighthouseapp.com/projects/27881/tickets/69-bug-in-asidatacompressor), contains a fix.

**Comment by pokeb** [comment]
Fix bug with ASIDataCompressor / ASIDataDecompressor
Thanks to Thomas Rasch for the fix!
Closed by 9fb62406c2c9076169773277f392abd4eeca0ea2
[#69 state:resolved]
