### ISSUE TITLE
Cached data isn't cleared properly because of file extension inconsistency

### ISSUE THREAD

**Issue by antonholmquist** [pokeb/asi-http-request#114]
Both pathToStoreCachedResponseDataForRequest and pathToCachedResponseDataForURL try to preserve the url extension in the response data file path, and otherwise adds the extension "html".

clearCachedResponsesForStoragePolicy only clears files with extension "cacheddata" or "cachedheaders" which won't match because of the preserved extensions.

Wouldn't a good solution be to just remove the file extension condition in clearCachedResponsesForStoragePolicy and delete all files in the cache directory for the specified storage policy?

<code>
if ([extension isEqualToString:@"cacheddata"] || [extension isEqualToString:@"cachedheaders"])
</code>

**Comment by pokeb** [comment]
Fix clearing cached data in clearCachedResponsesForStoragePolicy: (closed by eb30c1215d8a1106dc9ee59372783c3a2a525654)
Tweak tests that rely on invalid urls to make them work to make them more reliable

**Comment by pokeb** [comment]
Many thanks for catching this!
