### ISSUE TITLE
ASIDataDecompressor.m bug related to zlib error -2

### ISSUE THREAD

**Issue by ghost** [pokeb/asi-http-request#119]
I have faced strange behavior when you call [request responseData] it will return nil .. I have investigated this issue it appears that when zlib decompress the response data ,the allocated buffer needs only one byte in order to return a correct decompressed data other wise zlib reporting an error -2 and return nil data

I have found a solution to fix this bug in (uncompressBytes:length:error:) method
in line 72:
NSUInteger halfLength = length/2;  ---> NSUInteger halfLength = length/2+1;

**Comment by ghost** [comment]
It might be linked to https://github.com/pokeb/asi-http-request/issues/#issue/116

**Comment by pokeb** [comment]
Hi irami

Yes, I suspect these are likely to be the same issue.

If you can post a url that triggers the zlib issue, I'll take a look.

Best

Ben
