### ISSUE TITLE
ASIWebPageRequest UTF-8 failure when using a replacement mode different from ASIDontModifyURLs

### ISSUE THREAD

**Issue by 0xced** [pokeb/asi-http-request#126]
Try this page with the ASIHTTPRequest Demo app (Web Page Download):  
http://pitaya.ch/radar/martine.html  

Expected: **Martine écrit en UTF-8**  
Actual: **Martine Ã©crit en UTF-8**  

The data is written with `xmlSaveDoc(saveContext, doc);` in [ASIWebPageRequest.m:288](https://github.com/pokeb/asi-http-request/blob/v1.8/Classes/ASIWebPageRequest.m#L288)

I don't know if the encoding error happens at reading time or at writing time.

**Comment by 0xced** [comment]
The problem is at reading time: passing NULL for the encoding to `htmlReadFile` and `htmlReadMemory` is not a good idea. Patch is coming soon.

**Comment by 0xced** [comment]
Here it is: [pull request 127](https://github.com/pokeb/asi-http-request/pull/127)

**Comment by pokeb** [comment]
Fixed merged, closing.
