### ISSUE TITLE
Handling of 206 responses and support for "If-Range" conditional GET

### ISSUE THREAD

**Issue by 0xced** [pokeb/asi-http-request#131]
`-[ASIDownloadCache storeResponseForRequest:maxAge:]` should handle [206 Partial Content](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.7) responses. As of now, canceling and resuming a download does not save the cached headers.

Related: it would be nice to support the [If-Range](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.27) conditional GET when using `allowResumeForFileDownloads` and a download cache.

**Comment by kemenaran** [comment]
Agree.

At least a 206 response shouldn't cause the request to fail.
