### ISSUE TITLE
Look into problems with background tasks

### ISSUE THREAD

**Issue by pokeb** [pokeb/asi-http-request#137]
https://groups.google.com/forum/#!topic/asihttprequest/n4-9KXBlF1A

**Comment by pokeb** [comment]
Hmm.

From Jason's comment in the google group, and reading the docs, it sounds like this is not actually an issue, and the behaviour of background tasks is pretty sensible:

backgroundTimeRemaining:
"While the application is running in the foreground, the value in this property remains suitably large. If the application starts one or more long-running tasks using the beginBackgroundTaskWithExpirationHandler: method and then transitions to the background, the value of this property is adjusted to reflect the amount of time the application has left to run."

and:

beginBackgroundTaskWithExpirationHandler:
"You can call this method at any point in your application’s execution."

Closing for now, if anyone can provide concrete steps to reproduce the posters issue(s), please re-open.

Ben

**Comment by carsonreinke** [comment]
Ben-

I think I see the root issue with this problem.  Basically, a redirect will cause instance variable "backgroundTask" to be overwritten and even if the handler is setup, it will be calling "endBackgroundTask" on the latest task, not the original one.

``` objective-c
        #if TARGET_OS_IPHONE && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_4_0
        if ([ASIHTTPRequest isMultitaskingSupported] && [self shouldContinueWhenAppEntersBackground]) {
            if (!backgroundTask || backgroundTask == UIBackgroundTaskInvalid) { //<-- Added
                backgroundTask = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:^{
                    // Synchronize the cleanup call on the main thread in case
                    // the task actually finishes at around the same time.
                    dispatch_async(dispatch_get_main_queue(), ^{
                        if (backgroundTask != UIBackgroundTaskInvalid)
                        {
                            NSLog(@"Stopping %u: %@", backgroundTask, self.url);
                            [[UIApplication sharedApplication] endBackgroundTask:backgroundTask];
                            backgroundTask = UIBackgroundTaskInvalid;
                            [self cancel];
                        }
                    });
                }];
                NSLog(@"Starting %u: %@", backgroundTask, self.url);
            }
        }
        #endif
```
