### ISSUE TITLE
ASINetworkQueue will call queueDidFinish selector before a request's completion block

### ISSUE THREAD

**Issue by nsxdavid** [pokeb/asi-http-request#138]
If a request has a completion block, this gets called out of order with a  ASINetworkQueue's queueDidFinish delegate callback.  This is because 

ASINetworkQueue will call queueDidFinish selector before a request's completion block.

So you cannot reliably use this event to know when it is safe to discard the request delegate when using blocks.

**Comment by jpeyer** [comment]
I am experiencing this issue as well. I found this email on the mailing list, too: http://groups.google.com/group/asihttprequest/browse_thread/thread/3ef02ce3896efe77

**Comment by pokeb** [comment]
The order has been tweaked now. The queue should be called after the block.

Thanks!

Ben
