### ISSUE TITLE
Performance tips

### ISSUE THREAD

**Issue by steipete** [pokeb/asi-http-request#144]
You should add a section of tipps and tricks to improve performance in asi-http-request compared to the more lightweight NSUrlConnection.

For example, I discovered that building the User-Agent for every request is pretty heavy (NSBundle calls are expensive) - caching this and manually setting with the request helped quite a lot performance-wise.

And I'm sure there is more.

++
Peter

**Comment by pokeb** [comment]
Hi Peter

I have been meaning to do this for ages, I just need to find the time... :)

The user-agent thing has been sorted now at least.

I haven't done any profiling against NSURLConnection for a long time, though there are some very basic benchmarks in the tests. If you find any more specific areas where you think there are easy performance wins, do post them here! :)

Best,

Ben

**Comment by steipete** [comment]
Hi Ben,

thanks, I guess the user-agent stuff was the heaviest part, it's fast enough for me, but proper benchmarks would be a great thing, maybe I'll find some time. (but currently working on some contract stuff so...)

If i find anything, i'll report it here. Closing the issue now.
- Peter
