### ISSUE TITLE
Bad Internet == Force Crash

### ISSUE THREAD

**Issue by justAnotherDev** [pokeb/asi-http-request#146]
When the device has a very low network speed, say 5kb/s, and a startSynchronous is done on a large file, the request will try for about 20 seconds (no matter what you set your timeout to) and then force crash the app w/o any visible error. 

To replicate this you will need to throttle your computers speed by opening terminal (assuming you are on a mac):
sudo ipfw pipe 1 config bw 5KByte/s
sudo ipfw add 1 pipe 1 src-port 80

The code I am using is very basic, an empty project (4.2) with ASIHTTPRequest included.
    -(void)viewDidLoad {
        [super viewDidLoad];
        NSURL *aUrl = [NSURL URLWithString:@"http://ubiquitymobile.s3.amazonaws.com/example.json"];
        ASIHTTPRequest *aRequest = [ASIHTTPRequest requestWithURL:aUrl];
        [aRequest startSynchronous];

```
    //will crash before return is reached
    return;
}
```

to turn off the network throttling:
sudo ipfw delete 1

This crash has caused us a loooooot of problems because our app is used in high population areas (like football games and nascar events) where connectivity can be drawn to a halt. Our devs are working to dig through the code to find the issue, however it is not jumping out at us.

**Comment by pokeb** [comment]
Hi

Thanks for the report. I haven't been able to reproduce with the code above (different url), it just sits there, going very very slowly. Were you able to reproduce on the simulator?

Is there any thing in the device logs or console that indicates what happened?

Is there a reason you are using synchronous requests? Are these on the main thread?

Thanks

Ben
