### ISSUE TITLE
ASIDownloadCache + (id)sharedCache not thread safe

### ISSUE THREAD

**Issue by martijnthe** [pokeb/asi-http-request#148]
Hi Pokeb,

We're using [ASIDownloadCache sharedCache] on multiple background threads and noticed the implementation is not thread safe. I'm not sure whether we're using the method as intended though. We fixed it for our case by wrapping the implementation with @synchronized(self){ }.

Cheers,
Martijn

**Comment by pokeb** [comment]
Hi Martijn

I must confess I never really know what's best in these circumstances. I suppose for safety everything like this should be wrapped in a lock or synchronized, but it seems like it's a bit of a waste when this will (usually) only be set once in the whole app. If you did this on startup from the main thread, I don't think you shouldn't ever need to worry about this?

I guess another possibility would be to create the shared cache from initialize.

As ever, I'd welcome wiser opinions than my own... :)

Best,

Ben

**Comment by boxerab** [comment]
See this pull request for a solution:  https://github.com/pokeb/asi-http-request/pull/175
