### ISSUE TITLE
Redirect doesnt work with request->start

### ISSUE THREAD

**Issue by alexfs** [pokeb/asi-http-request#15]
When working with asynchronous requests in a single thread mode redirect requests get quietly dropped without completion

**Comment by pokeb** [comment]
Hi

Thanks for your report. Are you using the concurrent branch? If so, there are quite a few problems with it at the moment, but I'm working on making it stable again atm.

Thanks

Ben

**Comment by pokeb** [comment]
The concurrent branch has now been merged into master. Please post a new issue if you're still having problems.

Thanks

Ben

**Comment by alexfs** [comment]
Thanks Ben,

I'll give it a try.
