### ISSUE TITLE
10.6 API used

### ISSUE THREAD

**Issue by daveverwer** [pokeb/asi-http-request#16]
This may not be a bug and it may be the intention that ASIHTTPRequest is targeting 10.6 only now but line 3458 of ASIHTTPRequest.m calls:
- (id)dateByAddingTimeInterval:(NSTimeInterval)seconds

Which is a 10.6 API.

**Comment by pokeb** [comment]
Hi Dave

Many thanks for catching this, builds on 10.5 should be working again now.

Best

Ben

**Comment by daveverwer** [comment]
My pleasure! If I was actively using that bit of code I would even have supplied a patch :) Thanks for the speedy fix and for the code in the first place!
