### ISSUE TITLE
strange handling of session

### ISSUE THREAD

**Issue by kukosk** [pokeb/asi-http-request#160]
Hi,

I have a big problem. When i start my app, I do two requests. One is for login, so i send my username and password. My server responds fine (im logged in). And the second one is loading some data. The two requests are started at the same time. The problem is probably the response time. it seems like when the 'load data' request starts first and ends secondso it's like:
1. start 'load data'
2. start 'login'
3. finish 'login' - (it says im logged in successfully)
4. finish 'load data'

it seems like my app thinks i'm logged in, but i'm not.
when i try to make a request and the server responds with $_SESSION['login'], it's empty ...
when i don't make the 'load data' request, everything is okay ... when i do it after the 'login' request ends, it's okay, too. so it seems to be a problem only when i start the requests at the same time ....

I encountered the problem when my app was buggy. I started it up, and sometimes it worked, and sometimes not. I started to log the responses and saw that it somehow depends on the order of the requestsDidFinish for those two requests.

I can say it's 100% not bug on my server-side script as i'm using it also on other platforms this way, and don't have such problems.

Thanks for your response... and hope you solve it soon :)

**Comment by pokeb** [comment]
Hi Jakub

If I'm understanding correctly, I don't think this is a bug in ASIHTTPRequest.

I'm assuming you're sending credentials with a form post or something similar. If you need your login request to set up a logged in session that other requests will use, you must run it first, and make sure you get back the response from the login request before you start any other requests (for example, if your requestFinished: delegate method for the login request, start other requests).

If you're running requests asynchronously, there's no guarantee that they'll complete in any particular order. Also, if you start your requests at the same time, and you're handling authentication with a session cookie, there's a strong chance the second request won't even have a session id cookie yet if you haven't talked to the server before.

Best,

Ben

**Comment by kukosk** [comment]
Hi pokeb,

No it's not like that. When i open my app, and the first screen appears, it does a request (to load some data) but that one doesn't require user login, so it doesn't depend on the order of requestFinished: and I do user login on appDidBecomeActive: so those two request starts (approximately) at the same time. And now, my server returns loginstatus=TRUE, so my iPhone thinks im logged in, then the data comes back, so I can show them. but when i click on another tab (it's a tabbar app) which requires user login, the data isn't loaded, and when i log the output, i can see it's because im not logged in. Again, the request im doing in the same time as the login request doesn't require the user to be logged in. So I don't think it's my bug ;) If it was like that, I wouldn't write.

**Comment by pokeb** [comment]
Hi again

Ok, just to make sure I understand:
- You've have two requests that run at startup, one to login, and one that doesn't require login and is unrelated
- After the login request has returned and confirmed you are logged in, you issue another request from a different part of the app that does require login, but it comes back telling you that you aren't logged in.
- If you remove the other unrelated request on startup and just do the login, it works ok.

Is that right?

If so, off the top of my head:
- If the initial request that loads data does so from a script on the server, make sure it isn't modifying the session (or creating a new one)
- Try logging [request requestCookies] and [request responseCookies] for each request to make sure they're using the same session.

Best,

Ben

**Comment by kukosk** [comment]
Yes, you are true. It's as you wrote.
I tried logging the request and response cookies, and as I'm looking they are not the same for those two requests. It's kinda strange. In php I just do session_start(); on the beginning, and as far as I know, this doesn't overwrite the session ID, it just tells php im gona use session stuff (and it doesn't log me out on the web, so it should be ok).

2011-04-11 12:37:12.872 BraceletBook[5490:207] login request start: (
)
2011-04-11 12:37:12.897 BraceletBook[5490:207] data request start: (
)
2011-04-11 12:37:13.505 BraceletBook[5490:207] data request end: (
    "<NSHTTPCookie version:0 name:@\"PHPSESSID\" value:@\"63f53c23b0f59939******\" expiresDate:@\"(null)\" created:@\"324214634.000000\" sessionOnly:TRUE domain:@\"braceletbook\" path:@\"/\" secure:FALSE comment:@\"(null)\" commentURL:@\"(null)\" portList:[]>"
)
2011-04-11 12:37:13.683 BraceletBook[5490:207] login request end: (
    "<NSHTTPCookie version:0 name:@\"PHPSESSID\" value:@\"0ea2b7e64ea6e879*****\" expiresDate:@\"(null)\" created:@\"324214634.000000\" sessionOnly:TRUE domain:@\"braceletbook\" path:@\"/\" secure:FALSE comment:@\"(null)\" commentURL:@\"(null)\" portList:[]>"
)

// Here, i need the user to be logged in. This time, it returned the correct results, but where are the cookies ?
// sometimes it returns it just fine, and sometimes not.
// It's the same viewcontroller, so im logging them the same way as before^^
2011-04-11 12:37:38.236 BraceletBook[5490:207] data request start: (
)
2011-04-11 12:37:39.488 BraceletBook[5490:207] data request end: (
)

dont look on the domain, i was testing it on my localhost ;)

**Comment by kukosk** [comment]
maybe if those two are run from another thread, i dunno :) but I really don't understand why the last request seems to be without cookies, and returns my todos. Ain't it strange ? Cause it returns the correct ones.

**Comment by kukosk** [comment]
Hi pokeb, did you solve this thing somehow ?
