### ISSUE TITLE
Why is the default timeout 10 seconds?

### ISSUE THREAD

**Issue by danthorpe** [pokeb/asi-http-request#161]
Hi, Ben, great framework, thanks a lot.

I have a quick question, why is the default timeout only 10 seconds? The default for NSURLRequest is 60? I seem to get quite a few timeout errors when testing on an iPhone, is there any problem with just setting the default to 60?

Thanks, Dan

**Comment by pokeb** [comment]
Hi Daniel

I chose 10 seconds because it seemed like a reasonable amount of time to wait for something to happen without annoying users. Requests only timeout when no data is sent or received for 10 seconds, and it's very easy to change the default (if, for example, you expect a server to take a while to respond).

What do you think the default timeout should be?

Best,

Ben

**Comment by danthorpe** [comment]
Well, yesterday, I watched the two networking talks from 2010's WWDC, where they mentioned that the defaul NSURLRequest timeout is 60 seconds (I double checked, it still is). I'm guessing Apple have a reason for choosing it to be this large. I think it's because on the iPhone it can take a number of seconds for the link to become active again, so if you timeout too soon (just as the cell/wifi becomes active) then the app will be returning an error unnecessarily and draining battery.

Additionally, I don't think there is anything to be lost having a longer timeout, as while the request is sat waiting, (when implemented correctly) it's just waiting for an event to fire and shouldn't be blocking any threads.

I appreciate the framework is for Macs too, but from developing my own app, I'm finding that on the simulator, having 10 as the default is not a problem at all, but on the device, when the link is significantly more variable - it times out quite a lot. I've only recently just changed the default to 60 to see how it goes, so, not sure what it should be yet, I suspect somewhere between? 60 does sound like a long time.

On a related note, I've not looked through ASIHTTPRequest enough yet, but does it automatically retry requests that fail?

**Comment by steipete** [comment]
You can always set the timeout time to any number you like.

Ben, please leave it at 10 seconds. It's a reasonable number and working great.

**Comment by 0xced** [comment]
10 seconds is a good value. I think NSURLRequest default timeout should not be 60 seconds on iOS!

**Comment by pokeb** [comment]
@danthorpe - I can understand where you're coming from.

I think this is one of those things where one size doesn't fit all. ASIHTTPRequest was originally written for desktop Mac OS, where broadband is probably the norm. It is more likely that a connection on iOS will have much higher latency, which could lead to more timeouts.

I think it's important to think about how a particular network operation fits into your application. For a call in the background that wasn't directly initiated by the user (for example, checking for new data automatically every minute or so), it might make sense to increase the timeout if you know the user may well be connecting over a slow or unreliable connection (eg WWAN). Another situation where increasing the timeout would make sense would be if you know the server you are connecting to may be slow to respond.

IMO, if a network operation was started by the user, it's important that your app provides prompt feedback on what is happening. For example, if I tap refresh on my twitter timeline, I don't want to stare at the screen for 60 seconds before the app can tell me my connection isn't good enough to fetch an update. In my apps, I'd much rather operations fail early and not waste the users time waiting for a request that may not succeed anyway.

Timeouts are a fact of life on WWAN, and there are times when increasing the timeout will only serve to delay an inevitable failure. If you're downloading large amounts of data, it's always worth turning on resuming if your server supports it for the resource you are downloading.

Regarding automatic retries - yes, ASIHTTPRequest does support them, but you have to turn them on - see http://allseeing-i.com/ASIHTTPRequest/How-to-use#automatically_retry_requests_when_they_time_out

Best,

Ben

**Comment by danthorpe** [comment]
@pokeb Thanks Ben, and I completely agree with you, and I think this matches up with what Apple suggest too. 

I think on the desktop 10 is perfect, and indeed when testing my code in the simulator, it's fine. Interestingly, on iPhone, even on my Wifi, I get timeouts, so I think 10 is a bit low on iPhone. Consequently, on iOS, I think the best practice is to up the default a little bit, to 20 or 30 seconds. And then adjust the timeout for individual requests based on their context (unsolicited vs solicited for example).

Thanks again for the library!

**Comment by ipreencekmr** [comment]
I am having problem in timeout for URL Session / URL Request. I am getting timeout after 10 seconds in ios 11 even if I am not providing any timeout value. If providing, it has no effect on that connection. URLRequest works perfect on ios 9.0 but not on ios 11.
