### ISSUE TITLE
Indicate in SSL error message that wrong device date could cause this

### ISSUE THREAD

**Issue by olegam** [pokeb/asi-http-request#164]
We had a hard time figuring out why some iPod Touches got the "A connection failure occurred: SSL problem (possibly a bad/expired/self-signed certificate)" error. Turned out the date of those devices were all wrong. So we hint that this can be the issue in the alert we now show users. I think it would be helpful to write that information somewhere. Maybe by changing the messages to:
"A connection failure occurred: SSL problem (possibly a bad/expired/self-signed certificate) or wrong device date".

**Comment by pokeb** [comment]
Ok, if it saves someone a few hours of pain, then it's worthwhile. :)

**Comment by corymsmith** [comment]
Definitely saved me some time, I was just here to download the latest version and saw this commit message which solved an issue I hadn't resolved yet :)
