### ISSUE TITLE
Xcode 4 static analyzer claims that there's a dead code in line 4329 of ASIHTTPRequest.m

### ISSUE THREAD

**Issue by petejkim** [pokeb/asi-http-request#165]
Xcode 4 static analyzer claims that there's a dead code in line 4329 of ASIHTTPRequest.m, in +base64forData:

```
NSInteger i;
for (i=0; i < length; i += 3) {
  NSInteger value = 0;
  NSInteger j;
  for (j = i; j < (i + 3); j++) { // <---- static analyzer claims that the left operand to '+' (i) is always 0
    value <<= 8;
```

As far as I can tell, the code does not have any problem. Any way to get around this?

**Comment by pokeb** [comment]
Hi Peter

Not quite sure I understand why it was doing this, but I've reworked it to avoid the warning.

Best,

Ben
