### ISSUE TITLE
crash in ASIDownloadCache.m

### ISSUE THREAD

**Issue by rudraFury** [pokeb/asi-http-request#169]
Hi. I have a crash in the method below.
- (NSString *)keyForURL:(NSURL *)url
  {
  NSString *urlString = [url absoluteString];
  
  ```
  if([[urlString substringFromIndex:[urlString length]-1] isEqualToString:@"/"])
      urlString = [urlString substringToIndex:[urlString length]-1];
  ```
  
  const char *cStr = [urlString UTF8String];
  unsigned char result[16];
  CC_MD5(cStr, (CC_LONG)strlen(cStr), result);
  return [NSString stringWithFormat:@"%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X",result[0], result[1], result[2], result[3], result[4], result[5], result[6], result[7],result[8], result[9], result[10], result[11],result[12], result[13], result[14], result[15]];  
  }

I have added one more if. Hope this helps to someone.
- (NSString *)keyForURL:(NSURL *)url
  {
  NSString *urlString = [url absoluteString];
  
  if(urlString.length > 0)
      if([[urlString substringFromIndex:[urlString length]-1] isEqualToString:@"/"])
          urlString = [urlString substringToIndex:[urlString length]-1];
  
  const char *cStr = [urlString UTF8String];
  unsigned char result[16];
  CC_MD5(cStr, (CC_LONG)strlen(cStr), result);
  return [NSString stringWithFormat:@"%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X",result[0], result[1], result[2], result[3], result[4], result[5], result[6], result[7],result[8], result[9], result[10], result[11],result[12], result[13], result[14], result[15]];  
  }

**Comment by pokeb** [comment]
Fixed now, many thanks!
