### ISSUE TITLE
Little bug in line 1739 of ASIHTTPRequest.m

### ISSUE THREAD

**Issue by martijnthe** [pokeb/asi-http-request#17]
Little bug in line 1739 of ASIHTTPRequest.m:

NSLog(@"Request will redirect (code: %hi): %@", self, [self responseStatusCode]);

Should be:

NSLog(@"Request will redirect (code: %hi): %@", [self responseStatusCode], self);

**Comment by pokeb** [comment]
Hi martijnthe

Thanks for the report. I think this was actually fixed fairly recently:

http://github.com/pokeb/asi-http-request/commit/1fce43664e0c7c0cd040939d1953090679961322

Best

Ben
