### ISSUE TITLE
ASICache Performance Issue

### ISSUE THREAD

**Issue by myell0w** [pokeb/asi-http-request#173]
I found that loading from the cache takes a long time, longer than it should be. I initialized the cache-relevant part of my request like this:

```
[request setDownloadCache:[ASIDownloadCache sharedCache]];
[request setCacheStoragePolicy:ASICachePermanentlyCacheStoragePolicy];
[request setSecondsToCache:MTTimeIntervalDays(7)];
[request setCachePolicy:ASIAskServerIfModifiedWhenStaleCachePolicy];
```

I did a quick profiling with Instruments and it tells me that the following calls are the bottleneck:

```
[ASIDownloadCache canUseCachedDataForRequest:]
  |_  [ASIDownloadCache isCachedDataCurrentForRequest:]
            |_ [ASIHTTPRequest dateFromRFC1123String:]
```

Image of the call-tree from Instruments:

https://skitch.com/m.yellow/rhrjg/instruments3.png-100-layer-0-rgb-8

Any suggestions?

**Comment by pokeb** [comment]
I've made some internal changes to ASIDownloadCache to remove the need for the NSDateFormatter, so hopefully this should speed things up.

Many thanks! :)

Ben

**Comment by myell0w** [comment]
Thank you, performance is much better now when loading from cache!
