### ISSUE TITLE
ASIWebPageRequest Little Memory Leak

### ISSUE THREAD

**Issue by averello** [pokeb/asi-http-request#174]
In the file ASIWebPageRequest.m  of version 1.8(lines 371-375 for this version) there is this piece of code
near the end of the method
- (void)finishedFetchingExternalResources:(ASINetworkQueue *)queue

if ([self isResponseCompressed]) {
    NSMutableDictionary *headers = [[self responseHeaders] mutableCopy];
    [headers removeObjectForKey:@"Content-Encoding"];
    [self setResponseHeaders:headers];
}

and the property is declared like this 

@property (retain) NSDictionary *responseHeaders;

I found the leak using Instruments
a leak that can be fixed by adding the line 
[headers release];

Result : 
if ([self isResponseCompressed]) {
    NSMutableDictionary *headers = [[self responseHeaders] mutableCopy];
    [headers removeObjectForKey:@"Content-Encoding"];
    [self setResponseHeaders:headers];
    [headers release];
}

**Comment by pokeb** [comment]
Nice catch, many thanks! :)
