### ISSUE TITLE
Add a tag property to ASIHTTPRequest

### ISSUE THREAD

**Issue by Ricardo1980** [pokeb/asi-http-request#179]
It can be useful if ASIHTTPRequest have a tag property where mark requests, for instance:
# define kRequestUploadPicture 0
# define kRequestUploadThumbnail 1

ASIS3ObjectRequest\* request = [ASIS3ObjectRequest PUTRequestForData:data withBucket:S3_BUCKET key:filename];
request.tag=kRequestUploadPicture;];
[request setDelegate:self];
[request startAsynchronous];

Using a tag for this purpose is easier and faster than adding a parameter to userInfo.

**Comment by pokeb** [comment]
Had been thinking about doing this for a while...many thanks :)
