### ISSUE TITLE
ResponseString is empty when response code is 4xx

### ISSUE THREAD

**Issue by ericcxu** [pokeb/asi-http-request#182]
The responseString and responseData is nil when error delegate is called. According to the thread below, this is not by design, but a bug.  I have the same need as Johan, i.e. to parse response body when status code is 4xx, in some cases 500 too.

http://groups.google.com/group/asihttprequest/browse_thread/thread/f0e67cae19f1eea9/fd03c65d99eef298?show_docid=fd03c65d99eef298

Thanks,
Eric

**Comment by pokeb** [comment]
Fixed now, many thanks!
