### ISSUE TITLE
S3 BUG parse problem with Blocks

### ISSUE THREAD

**Issue by gwdp** [pokeb/asi-http-request#185]
Hi there , I'm using ASI S3 classes to connect throw amazon S3 under blocks . I'm having an issue that when running an SYNC ASIS3 connection that returns something that ins't only the response code the parse runs in other thread , so I 'solve' BY NOW this issue giving sleeping my thread for while .

So If I'm doing something wrong please tell me , but I thing it's ASI issue ....

Below is one of those methods that is runnig in this problem .

``` obj-c
//
+ (void)listBucketsEndingBlock:(void(^)(NSArray *list,BOOL sucess,NSError* error))endBlock {
    //
    dispatch_async(AsynQueue, ^{
        //
        NSAutoreleasePool * pool = [[NSAutoreleasePool alloc]init];
        //
        [ASIHTTPRequest clearSession];
        //
        ASIS3ServiceRequest *request = [ASIS3ServiceRequest serviceRequest];
        [SyncConnections configS3Request:&request withHTTPS:YES];
        //
        [request startSynchronous];
        #warning BUG WORKAROUND
        [NSThread sleepForTimeInterval:1];
        //
        if (![request error]) {
            //
            NSMutableArray * array = [[NSMutableArray alloc]init];
            //
            for (ASIS3Bucket * obj in request.buckets) {
                //
                [array addObject:[NSDictionary dictionaryWithObjectsAndKeys:obj.ownerName,@"ownerName",obj.ownerID,@"ownerID",obj.name,@"name",obj.creationDate,@"creationDate",nil]];
                //
            }
            //
            endBlock([array autorelease],YES,nil);
            //
        }
        //
        else {
//            NSLog(@"SyncConnections - error in %s with error - %@",__PRETTY_FUNCTION__,[request error]);
            endBlock(nil,NO,[[[request error]copy]autorelease]);
        }
        //
        [pool release];
        //
    });
    //
}

```

hmmm defaultQueue is 
`#define AsynQueue dispatch_get_global_queue(0, DISPATCH_QUEUE_PRIORITY_DEFAULT)`

**Comment by pokeb** [comment]
I'm not certain I understand the problem, but since you're already using blocks, it would probably make a lot more sense to use asynchronous requests and ASIHTTPRequest's blocks API - you can loop through the buckets from the request's completionBlock. See: http://allseeing-i.com/ASIHTTPRequest/How-to-use#using_blocks

Best

Ben
