### ISSUE TITLE
Dead code in ASIDownloadCache.m:175

### ISSUE THREAD

**Issue by petejkim** [pokeb/asi-http-request#189]
```
// We'll change 304/Not Modified to 200/OK because this is likely to be us updating the cached headers with a conditional GET
int statusCode = [request responseStatusCode];
if (statusCode == 304) {
    statusCode = 200;
}
[responseHeaders setObject:[NSNumber numberWithInt:[request responseStatusCode]] forKey:@"X-ASIHTTPRequest-Response-Status-Code"];
```

statusCode is never used.
Did you mean to do

```
[responseHeaders setObject:[NSNumber numberWithInt:statusCode] forKey:@"X-ASIHTTPRequest-Response-Status-Code"];
```

Thanks.

**Comment by gbuesing** [comment]
FYI, this shows up as an issue when you run Analyzer on the ASI iPhone project.

**Comment by iamleeg** [comment]
Yup, just came here to post a diff, but see this issue already exists :). Oh well, I wrote the diff anyway:

diff --git a/Classes/ASIDownloadCache.m b/Classes/ASIDownloadCache.m
index 4854c91..fdbd42e 100644
--- a/Classes/ASIDownloadCache.m
+++ b/Classes/ASIDownloadCache.m
@@ -174,7 +174,7 @@ static NSString *permanentCacheFolder = @"PermanentStore";
        if (statusCode == 304) {
                statusCode = 200;
        }
-       [responseHeaders setObject:[NSNumber numberWithInt:[request responseStat
- ```
    [responseHeaders setObject:[NSNumber numberWithInt: statusCode] forKey:@
  
  [responseHeaders writeToFile:headerPath atomically:NO];
  ```

**Comment by pokeb** [comment]
Many thanks all, fixed now! :)
