### ISSUE TITLE
Original URL not stored after redirect

### ISSUE THREAD

**Issue by martijnthe** [pokeb/asi-http-request#19]
It would be nice if the request would store the original URL.
When using a queue and requestDidFinish delegate methods, I usually check the url property of a request to figure out which resource has been downloaded. But if the request has been redirected, this fails.

**Comment by pokeb** [comment]
I've had requests for this so many times, I have no idea why I haven't got around to implementing this yet. Will do it today.

As a side note, you could also use the userInfo dictionary to work out which request your delegate is handling.

ta

b

**Comment by pokeb** [comment]
Ok, this is implemented now via the originalURL property.

Thanks

Ben
