### ISSUE TITLE
setUsername/password should update session, or need better documentation?

### ISSUE THREAD

**Issue by marcetcheverry** [pokeb/asi-http-request#193]
If you are using session persistence (by default it is), when you set a new username or password, it should update the session with those.

We spent several hours trying to figure out why ASIHTTPRequest was returning the same data when logging in with one user, and then another (when it should have returned different data based on the credentials).

It turned out we forgot to call [ASIHTTPRequest clearSession] before setting the new credentials.

This wasn't clear to us, we thought setting a username and password would update the current session. But there is no overridden setters for the username/password properties which updates the current session. A warning would have been nice at least.

**Comment by pokeb** [comment]
Hi Marc

I think this commit should have fixed this problem:

https://github.com/pokeb/asi-http-request/commit/37007b7bc1a26e2036fc03b3627cf616395a72bf

If you update your copy of ASIHTTPRequest, does it work?

Thanks

Ben

**Comment by marcetcheverry** [comment]
Thank you for the quick fix!.

I am not sure if we used a 1.8 tarball or a copy of master. I will try to check tomorrow if possible (not sure how, though, as I have only the source)

We should have been calling +clearSession in our code anyhow, so the bug was solved.

Is master safe to use in production code? I am not sure how ASI versioning works.

**Comment by pokeb** [comment]
Generally the most current master is the most stable version. New release tags like 1.8 are primarily about documenting what's changed recently, rather than being stable snapshots. Anyway, hopefully there will be a new release this weekend.

Best,

Ben

**Comment by marcetcheverry** [comment]
Confirmed fixed in master.
