### ISSUE TITLE
readStream null on occasion

### ISSUE THREAD

**Issue by prime31** [pokeb/asi-http-request#2]
I don't have really good reproduce instructions for you on this one because it is so rare but it does happen.  I use a standard NSOperationQueue to push all ASIHTTPRequests into and I push a lot of requests through it limited to 4 simulataneously.

Around line 717 of ASIHTTPRequest.m there are (rare) occasions when the readStream is NULL and
the following line crashes the app:

[self setTotalBytesSent:[[(NSNumber *)CFReadStreamCopyProperty(readStream, kCFStreamPropertyHTTPRequestBytesWrittenCount) autorelease] unsignedLongLongValue]];

**Comment by pokeb** [comment]
Hi 

Someone else reported a similar issue earlier this week. I have a what I hope is a fix sorted out, will push it up to GitHub tomorrow.

ta

Ben

**Comment by prime31** [comment]
Thanks Ben!  Sorry I didn't send a patch with the bug.  If only there
was more time in each day...

**Comment by pokeb** [comment]
I know the feeling... :)

**Comment by pokeb** [comment]
This fix is on GitHub now, do let me know if you are still having problems!

Thanks

Ben

**Comment by prime31** [comment]
Looks good to me so far after some testing.  Thanks Ben.

**Comment by pokeb** [comment]
Cool, will close the ticket.

Thanks again!

b

**Comment by rbsgn** [comment]
Ben, is there a way to link issue fix with commit id?
