### ISSUE TITLE
Fails to build on fresh checkout.

### ISSUE THREAD

**Issue by klacoste** [pokeb/asi-http-request#20]
Both the sample projects use a build script to set the version number post build. This refers to stuff not installed by default on Mac OS X thus causing the build to error out. Deleting the build script phase allows the build to complete.

**Comment by pokeb** [comment]
Hi Kevin

Can you let me know what version of Mac OS you're using? I was under the impression that Ruby has been bundled with Mac OS for a while, but perhaps you are missing the /usr/bin/env program? Let me know, and I'll try to figure out the best thing to do.

Thanks!

Ben

**Comment by pokeb** [comment]
I think this was fixed a while back - the script checks to see if it finds git at that path.
