### ISSUE TITLE
response data empty

### ISSUE THREAD

**Issue by aferre** [pokeb/asi-http-request#200]
Hi

When using an asynchronous request, the data property of an asihttprequest is always nil when a request is finished (in the requestFInished delegate function), but when using the received data delegate, it does return some stuff.

**Comment by tjarratt** [comment]
I would expect that the data property would be there for all ASIHttpRequests. In my projects, I use a lot of asynchronous requests and haven't seen this problem.

Is this new or have you always seen this behavior? I'm a little worried now to pull the latest from ToT in my projects.

**Comment by aferre** [comment]
I guess it's new, otherwise i would have definetly said something earlier.

If it is it must be a bug fix away from disappearing :) I'm waiting for pokeb to read this post

**Comment by aferre** [comment]
tjarratt : did you try the latest version?

**Comment by pokeb** [comment]
If your delegate implements request:didReceiveData:, responseData / rawResponseData / responseString will always be nil, as noted in the documentation:

http://allseeing-i.com/ASIHTTPRequest/How-to-use#handling_the_response_data_as_it_arrives

**Comment by aferre** [comment]
ok thanks. :$
