### ISSUE TITLE
Crash when checking for invalid URL in cache

### ISSUE THREAD

**Issue by jfmorin** [pokeb/asi-http-request#201]
Hi,

I think that an extra validation is required in the method keyForURL of ASIDownloadCache. If a nil URL is requested and the cache policy indicates to use the cache upon request error the call to the MD5 hash method will fail.

Something like this looks like a descent solution (validation and return added at the beginning of the method):
- (NSString *)keyForURL:(NSURL *)url
  {
  NSString *urlString = [url absoluteString];
  
  // The hash cannot be generated on an empty string. Will not find anything in cache anyway.
  if (url == nil || [urlString length] == 0) {
      return nil;
  }
  
  // Strip trailing slashes so http://allseeing-i.com/ASIHTTPRequest/ is cached the same as http://allseeing-i.com/ASIHTTPRequest
  if ([[urlString substringFromIndex:[urlString length]-1] isEqualToString:@"/"]) {
      urlString = [urlString substringToIndex:[urlString length]-1];
  }
  const char *cStr = [urlString UTF8String];
  unsigned char result[16];
  CC_MD5(cStr, (CC_LONG)strlen(cStr), result);
  return [NSString stringWithFormat:@"%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X%02X",result[0], result[1], result[2], result[3], result[4], result[5], result[6], result[7],result[8], result[9], result[10], result[11],result[12], result[13], result[14], result[15]];  
  }

Jeff

**Comment by almostabc** [comment]
I actually ran into this issue today because of a url that wasn't properly encoded. I came here to post the issue to find that the fix was posted yesterday! Please fix this in the main branch.

**Comment by pokeb** [comment]
Fixed now, thanks! :)
