### ISSUE TITLE
what is http 201 status created

### ISSUE THREAD

**Issue by insoftservice** [pokeb/asi-http-request#209]
What is http 201 status created response code, how to get the response via curl in php and how the o/p is obtained 
Sorry newbie to http 201  and github 
Say if the Task is in such format for eg

Input:
The following URL creates a new information
http://mangalsutrabandhan.com/dispatch_ws.php?action=create 
Expected POST data to create a new information is name and type

Web service returns HTTP 201 CREATED response code if information creation is successful

 Output:
Create a new information and output “OK” to the browser if and only if creation is successful

**Comment by pokeb** [comment]
Off topic, closing.
