### ISSUE TITLE
Body of an redirecting URL gets written and body of final URL gets appended to it

### ISSUE THREAD

**Issue by martijnthe** [pokeb/asi-http-request#22]
Hi again,

When using ASIHTTPRequest to download redirected URLs (e.g. 307, temporary redirect), the body of the redirecting URL gets saved to file (or memory). In my test case (http://download.omroep.nl/vpro/35551406.mp3), the redirecting URL's body contains html meta redirect code (as fallback for browsers ignoring the 307 HTTP status).

It seems to be solved when this condition is added at line 2478 in ASIHTTPRequest.m. Not sure if there are any malicious consequences though...

```
if ([self needsRedirect] == NO) 
    // Are we downloading to a file?
    if ([self downloadDestinationPath])
```

M

**Comment by martijnthe** [comment]
My solution wasn't complete. At line 2533 I added [self needsRedirect] == NO:

```
if ([self temporaryFileDownloadPath] && [self needsRedirect] == NO) {
    [[self fileDownloadOutputStream] close];
```

To prevent the stream from being closed in case the request is being redirected.

**Comment by pokeb** [comment]
Hi Martijn

I've finally got around to making some changes here, when automatic redirect is on and you are resuming, it should ignore the body of the redirecting response.

Best

Ben

**Comment by pokeb** [comment]
I think this is probably resolved, will close.

**Comment by franqueli** [comment]
Why are we ignoring the body of the redirecting response only if we a resuming? We're running into an issue where we make a request for a file to download. Our initial request just hits a server that redirects to the url for the file. We then check if a file exists at the specified download path to know if we need to request again or if we're done. This works fine except in one scenario. We've using an ASINetworkQueue to batch related downloads. If our app is going to terminate we kill the queue by  calling cancelAlOperations. If we don't specify resuming in the request then we get a callback telling us the queue has finished and when we check the filesystem we see a file in the specified download path. This file just has the contents of the redirect.  The file is placed there by the call to  [ASIDataDecompressor uncompressDataFromFile: toFile:   in the handleStreamComplete method of ASIHTTPRequest
- (void)handleStreamComplete
  ....
      if ([self shouldRedirect] && [self needsRedirect] && [self allowResumeForFileDownloads]) {
  
  ```
  } else if ([self isResponseCompressed]) {
  
      // Decompress the file directly to the destination path
      if ([self shouldWaitToInflateCompressedResponses]) {
          [ASIDataDecompressor uncompressDataFromFile:[self temporaryFileDownloadPath] toFile:[self downloadDestinationPath] error:&fileError];
  ```
