### ISSUE TITLE
Overriding existing cookies

### ISSUE THREAD

**Issue by tombrtls** [pokeb/asi-http-request#226]
It doesn't seem like the new responseCookies overwrite existing ones. For example we get a rememberMe session cookie which stays alive for 30 days, and each request to the service supplies a new rememberMe cookie, which it should set in the NSHTTPCookieStorage. But the next time a request is done it uses the older rememberMe cookie.

After some digging into the code, i came to the conclusion that the problem lies within the [[NSHTTPCookieStorage sharedHTTPCookieStorage] setCookies:newCookies forURL:[self url] mainDocumentURL:nil];  function within the readResponseHeaders method of ASIHTTPRequest. 

My workaround for now is using the following function for each cookie:
[[NSHTTPCookieStorage sharedHTTPCookieStorage] setCookie:cookiel];  (This method actually overrides the existing cookies if necessary).

**Comment by tombrtls** [comment]
As it turns out i was to quick to test this and it can take some time to set new cookies.

**Comment by xgalaxy** [comment]
Hello,

We are running into this problem as well. I'm curious why you chose to close this issue, as I believe not having the cookie update right away is an error.

How else am I supposed to know when it is safe to make another request, if my next requests rely on that cookie containing the most up to date data from the server?

If I implement the fix described in the original issue, are there any side effects to it?

Thanks.

**Comment by tombrtls** [comment]
Hi,

The problem with the delay is, from my understanding, is originated in the NSHTTPCookieStorage and not in the ASIHTTPRequest (http://lists.apple.com/archives/cocoa-dev/2011/Jul/msg00114.html). At this point there seems to be a delay in handling(inserting/replacing/deleting) cookies. This means follow-up request are not always using the proper cookies as they have not been set yet. 

A more suitable work around can be setting the cookies to the request manually to make sure it uses the latest (see Handling cookies yourself @ http://allseeing-i.com/ASIHTTPRequest/How-to-use).

Good luck
