### ISSUE TITLE
CDN Managment URL key

### ISSUE THREAD

**Issue by chrisozenne** [pokeb/asi-http-request#233]
I was having trouble making ASICloudFilesCDNRequests, kept getting a generic "Unable to start HTTP connection" error.

I was able to track down the bug to the following section of code in ASICloudFilesRequest.m:

```
68  if (![request error]) {
69  NSDictionary *responseHeaders = [request responseHeaders];
70  authToken = [responseHeaders objectForKey:@"X-Auth-Token"];
71  storageURL = [responseHeaders objectForKey:@"X-Storage-Url"];
72  cdnManagementURL = [responseHeaders objectForKey:@"X-Cdn-Management-Url"];
73  }
```

Obtaining cdnManagementURL using the key "X-Cdn-Management-Url" returned (null) and was causing other problems later on down the line. Turns out the correct key uses a capitalized "CDN" like so:

"X-CDN-Management-Url"

API Reference: http://docs.rackspace.com/files/api/v1/cf-devguide/content/Authentication-d1e639.html#d6e265

**Comment by greenisus** [comment]
I think that should be URL instead of Url.  I'll look into it when I wake up in about 8 hours :)

Mike Mayo - @greenisus

**Comment by chrisozenne** [comment]
Cool, let me know what you find.

**Comment by chrisozenne** [comment]
Another related issue came up for me... I made a call to this method:

<pre>
+ (id)putRequestWithContainer:(NSString *)containerName ttl:(NSUInteger)ttl;
</pre>

and my didFinishSelector looks like this because I wasn't getting a valid cdnURI back:

<pre>
- (void)cdnRequestDidFinish:(ASICloudFilesCDNRequest *)request {
        
    NSLog(@"cdnURI:%@",[request cdnURI]);
    NSLog(@"response headers = %@",[request responseHeaders]);
    
}
</pre>

The log output is as follows:

<pre>
2011-08-05 01:50:22.817 moshpic[1390:707] cdnURI:(null)
2011-08-05 01:50:22.818 moshpic[1390:707] response headers = {
    Connection = close;
    "Content-Length" = 0;
    "Content-Type" = "text/plain; charset=UTF-8";
    Date = "Fri, 05 Aug 2011 08:50:24 GMT";
    Server = Apache;
    "X-CDN-SSL-URI" = "https://c689863.ssl.cf2.rackcdn.com";
    "X-CDN-URI" = "http://c689863.r63.cf2.rackcdn.com";
}
</pre>

This is the call to cdnURI:

<pre>
- (NSString *)cdnURI {
    return [[self responseHeaders] objectForKey:@"X-Cdn-Uri"];
}
</pre>


As you can see your code is returning the object for the key "X-Cdn-Uri", but the response header that's being returned from the API is "X-CDN-URI".

**Comment by greenisus** [comment]
Okay I have this fixed.  Will try to get a pull request in today.

**Comment by greenisus** [comment]
It turns out older account say "Cdn" everywhere and newer accounts say "CDN"

**Comment by chrisozenne** [comment]
Yea, it's not that your code was asking for the wrong key, but that the key had changed on the API - but not for everyone. Might need to adjust the code to accept both cases in order to keep everyone's apps running smoothly.

Thanks for checking on this quickly.

**Comment by greenisus** [comment]
Yep, I'm going to push a fix that covers both cases.

Mike
901-299-9306
@greenisus
