### ISSUE TITLE
Leak in ASICloudFilesObjectRequest?

### ISSUE THREAD

**Issue by pokeb** [pokeb/asi-http-request#234]
@greenisus Just noticed the static analyzer in the latest Xcode beta picks this up, it looks like the dictionary probably needs to be autoreleased:

https://github.com/pokeb/asi-http-request/blob/master/Classes/CloudFiles/ASICloudFilesObjectRequest.m#L133

If so I'm happy to fix, but if you're looking at #233 anyway, are you ok to pick this up?

Thanks!

Ben

**Comment by greenisus** [comment]
i'll fix it!  thanks :)
