### ISSUE TITLE
*Feature Request* - ASIWebPageRequest - Update UIWebView as resources are downloaded rather than wait

### ISSUE THREAD

**Issue by ghost** [pokeb/asi-http-request#237]
ASIWebPageRequest currently waits until every resource from a web page has been downloaded before it can be used for rendering by UIWebView. The effect of this is that the user experience of using ASIWebPageRequest isn't as smooth as it could be. 

The desired behaviour is for ASIWebPageRequest to emulate how safari renders webpages.  Pages should be rendered as they are downloading to give the feeling of progress to the user, so HTML would be downloaded first and the UIWebView updated and then CSS would be downloaded and the UIWebView updated and finally any graphics would load and be displayed after that.

**Comment by pokeb** [comment]
For cases where you need to proxy or cache content while browsing in a UIWebView, you can use this project as a starting point:

https://github.com/pokeb/ProxyingUIWebView

Uses some of the same tricks as ASIWebPageRequest, but has less of the limitations and should be significantly faster in many cases.

Best,

Ben
