### ISSUE TITLE
Missing Reachability.h

### ISSUE THREAD

**Issue by azamsharp** [pokeb/asi-http-request#238]
your latest download files are missing Reachability.h files

**Comment by pokeb** [comment]
The reachability files should be in the External/Reachability folder, as noted in the documentation - are they not there for you?

Best,

Ben

**Comment by azamsharp** [comment]
Found them! My fault! Thanks!

On Wed, Aug 10, 2011 at 5:50 PM, pokeb <
reply@reply.github.com>wrote:

> The reachability files should be in the External/Reachability folder, as
> noted in the documentation - are they not there for you?
> 
> Best,
> 
> Ben
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pokeb/asi-http-request/issues/238#issuecomment-1777556

## 

Mohammad Azam
MVP (Most Valuable Professional)
www.highoncoding.com
www.azamsharp.com
Check out my iPhone app "ABC Pop" *
http://itunes.apple.com/us/app/abc-pop/id392527680?mt=8*http://itunes.apple.com/us/app/abc-pop/id392527680?mt=8
