### ISSUE TITLE
ASIWebPageRequest problem with .aspx pages

### ISSUE THREAD

**Issue by ransomweaver** [pokeb/asi-http-request#241]
I have ASIWebPageRequest fetching a page that is asp.net The code at line 244 of ASIDownloadCache.m creates some problems, in that it names the downloaded file .aspx, and this filetype is not understood by the UIWebView that I'm loading it into. My solution is to change the code in ASIDownLoad Cache like so:

// Grab the file extension, if there is one. We do this so we can save the cached response with the same file extension - this is important if you want to display locally cached data in a web view 
    NSString *extension = [[[request url] path] pathExtension];
    if (![extension length] || [extension isEqualToString:@"aspx"] || [extension isEqualToString:@"php"]) {
        extension = @"html";
    }

That will put .html on the end of the file, which is correct, as the file contains an html document.  There is probably be a more general purpose solution to this, other than trying to remember all the extensions that should be replaced with html.

**Comment by pokeb** [comment]
I have added some similar code that should solve this issue - many thanks! :)
