### ISSUE TITLE
Download Progress shouldn't be updated with redirecting URLs

### ISSUE THREAD

**Issue by martijnthe** [pokeb/asi-http-request#25]
When fetching an URL that gets redirected, de progress is set to 100% when the redirecting request finished. Then the progress is set back again to 0% when the new request (to which the other URL pointed) is started.

Better would be not to set the progress, until the headers are processed and it is known that the request is not redirected.

**Comment by pokeb** [comment]
Hey Martijn

I don't think this is a problem anymore as of v1.6.2, requests that redirect shouldn't update progress delegates. Please do re-open if you find you're still having problems.

Thanks!

Ben
