### ISSUE TITLE
ASIWebPageRequest, ASICloudFilesObjectRequest memory fixes

### ISSUE THREAD

**Issue by benoit-pereira-da-silva** [pokeb/asi-http-request#255]
ASIWebPageRequest line 372 [headers release] 
ASICloudFilesObjectRequest line 133 should be autoreleased

**Comment by pokeb** [comment]
I can't see either of these issues in the most recent code - perhaps they were fixed already?

**Comment by benoit-pereira-da-silva** [comment]
They are fixed now. Thanks
