### ISSUE TITLE
requestFailed sporadicaly

### ISSUE THREAD

**Issue by eliavm** [pokeb/asi-http-request#262]
Under a specific ISP I am getting sporadic requestFailed with http code 0. If I send the same request again and again it will go through and I'll get http code 200. About 20%-30% of my requests fail.

Under other ISPs I've tested, the app works great, no connection errors at all.

Is there anything to do? any idea how to debug this?

**Comment by greenisus** [comment]
There's really nothing you can do.  Any time a request fails with a 0 status code, I simply show an alert dialog telling the user to check his/her internet connection.
