### ISSUE TITLE
requestRedirectedBlock retain issue

### ISSUE THREAD

**Issue by BasitAli** [pokeb/asi-http-request#279]
I noticed in a recent project that when I set the requestRedirectedBlock, it is not released when the request is finished. The releaseBlocksOnMainThread method calls release on all blocks except requestRedirectedBlock. I added in the release and the controller that initialized the request is now releasing properly. Is it really an issue or am I missing something?

Oh and thanks for the brilliant library :).

**Comment by fpillet** [comment]
I've seen the same issue, ASIHTTPRequest is missing a release for its redirect block. Unfortunately, Ben stopped maintaining the code but you can fix it by adding this to - releaseBlockOnMainThread:

```
if (requestRedirectedBlock) {
    [blocks addObject:requestRedirectedBlock];
    [requestRedirectedBlock release];
    requestRedirectedBlock = nil;
}
```

**Comment by BasitAli** [comment]
Thanks, that's what I did to resolve the issue. But as suggested I would better move to a different library. Which one do you suggest? I've read that AFNetworking is a good choice to switch to.

**Comment by fpillet** [comment]
AFNetworking may be a good choice if its feature set suits you, and if you can afford requiring iOS 4.0 and up. I have not tried it though - have to keep some level of 3.x compatibility for the time being.

**Comment by jogu** [comment]
Fix merged - thanks!
