### ISSUE TITLE
Crash EXC_BAD_ACCESS when canceling requests

### ISSUE THREAD

**Issue by steipete** [pokeb/asi-http-request#28]
Hi, I'm getting sporadic crashes when canceling requests.

It crashes in startRequest: http://skitch.com/steipetee/n2w5q/xcode

I am stopping all current operations via
[networkQueue cancelAllOperations];

Am I doing something wrong?

**Comment by steipete** [comment]
I posted my problem here: http://allseeing-i.lighthouseapp.com/projects/27881-asihttprequest/tickets/47-crash-exc_bad_access-when-canceling-requests

**Comment by kjk** [comment]
It looks like your using ASIHTTPRequest object in one thread and canceling operations in another thread, which causes ASIHTTPRequest object to be destroyed hence the crash you're seeing (crash in objc_msgSend usually means using a deallocated object; you can use NSZombieEnabled (http://www.cocoadev.com/index.pl?NSZombieEnabled) to get a better picture of what happens).

Your code is not thread safe. You can either ditch the use of threads (ASIHTTPRequest claims to support async operations with everything running on main thread) or add a way to stop your thread before you call cancelAllOperations.

**Comment by pokeb** [comment]
Hi

It _ought_ to be safe to cancel requests from any thread, ASIHTTPRequest uses locks to stop this causing problems.

Though NSOperationQueue and ASINetworkQueue will run your request in a thread, 99% of the time, you shouldn't need to modify your design to take account of this.

If you can add the code you used to create and cancel requests to your bug report in lighthouse (or, even better, attach a sample project that demonstrates the problem), I'd be happy to take a look.

Thanks

Ben
