### ISSUE TITLE
Is there any branch with all these issues fixed?

### ISSUE THREAD

**Issue by Ricardo1980** [pokeb/asi-http-request#286]
Hello!

As you know, the author of this library said is not going to maintain it again, so I wonder if anybody there hasa branch with all the pull request added, that is many issues fixed.

Anyone?

Thanks a lot.

**Comment by Coeur** [comment]
This one looks not too bad:
https://github.com/yllan/asi-http-request

But it doesn't mean anything for the future.

**Comment by jogu** [comment]
Ben has granted a couple of people write access to the master repository, so it is probably best one use that one. (Things did get a bit behind for a while.)

Unfortunately (at least for me) I don't have much time to look at asihttprequest unless something comes up relevant to the project I'm working on, but if there's fixes that aren't in the master repository but do look right and fix a problem for you, please comment on them to say they seem right as that makes our life a bit easier when trying to figure out if things are okay to merge.
