### ISSUE TITLE
Is this normal: "[delegate respondsToSelector:didFailSelector]" Where is @selector?

### ISSUE THREAD

**Issue by Ricardo1980** [pokeb/asi-http-request#290]
Hello!

I don't know if this is an error.
Is it normal not having @selector in these lines?
- (void)reportFailure
  {
  if (delegate && [delegate respondsToSelector:didFailSelector]) {
      [delegate performSelector:didFailSelector withObject:self];
  }

From ASIHTTPRequest.m.

Same question for:

/\* ALWAYS CALLED ON MAIN THREAD! */
- (void)reportFinished
  {
  if (delegate && [delegate respondsToSelector:didFinishSelector]) {
      [delegate performSelector:didFinishSelector withObject:self];
  }

Thanks.

**Comment by yllan** [comment]
It's normal.

**Comment by Ricardo1980** [comment]
Can you explain me why? Why selector is not used? Thanks.

**Comment by yllan** [comment]
`didFinishSelector` here is an ivar. Its default value is `@selector(requestFailed:)`.

`[self setDidFailSelector:@selector(requestFailed:)];`

**Comment by jogu** [comment]
Yes, it's normal - the delegate call back code is a bit involved - if you look at a discussion on the mailing list ~18 months ago you can see some explanations of how/why it works like this.
