### ISSUE TITLE
sslProperties leak #1207 of ASIHTTPRequest.m

### ISSUE THREAD

**Issue by Horse888** [pokeb/asi-http-request#296]
I add autorelease to it.

NSDictionary *sslProperties = [[[NSDictionary alloc] initWithObjectsAndKeys:
                                      [NSNumber numberWithBool:YES], kCFStreamSSLAllowsExpiredCertificates,
                                      [NSNumber numberWithBool:YES], kCFStreamSSLAllowsAnyRoot,
                                      [NSNumber numberWithBool:NO],  kCFStreamSSLValidatesCertificateChain,
                                      kCFNull,kCFStreamSSLPeerName,
                                      nil] autorelease];

**Comment by Coeur** [comment]
Many people already requested this pull:
https://github.com/pokeb/asi-http-request/pull/282
https://github.com/pokeb/asi-http-request/pull/284
https://github.com/pokeb/asi-http-request/pull/288
https://github.com/pokeb/asi-http-request/pull/294

And many forks implement it:
https://github.com/yllan/asi-http-request/

**Comment by dirkdk** [comment]
I'd personally not do autorelease but release at the end of the block. And yes it's a nobrainer. XCode Analyzer reports it pretty nicely

**Comment by jogu** [comment]
Fix merged, thanks everyone.
