### ISSUE TITLE
Look again at proxies when using HTTPS

### ISSUE THREAD

**Issue by pokeb** [pokeb/asi-http-request#31]
It may be we need to set the stream properties differently when connecting to HTTPS urls.

**Comment by MrZoidberg** [comment]
Hi, I confirm that when I use proxy with Basic authentication and HTTPS urls for request ASIHTTPRequest works only with the following code at line 900:

NSMutableDictionary *proxyToUse = [NSMutableDictionary dictionaryWithObjectsAndKeys:[self proxyHost],kCFStreamPropertyHTTPSProxyHost,[NSNumber numberWithInt:[self proxyPort]],kCFStreamPropertyHTTPSProxyPort,nil];
        CFReadStreamSetProperty((CFReadStreamRef)[self readStream], kCFStreamPropertyHTTPProxy, proxyToUse);

**Comment by pokeb** [comment]
Hi Mihail

Thanks - can you update your copy, and let me know if it's working now? I've added in some code to change the dictionary keys when we're connecting to an https url.

Best

Ben

**Comment by MrZoidberg** [comment]
Hi Ben, now works correctly. Thanks!

**Comment by pokeb** [comment]
Great stuff! :)
