### ISSUE TITLE
initWithURL: should call [self init] rather than [super init]

### ISSUE THREAD

**Issue by atnan** [pokeb/asi-http-request#32]
You need to call self here or ASIHTTPRequest subclasses can't configure defaults by overriding -init. I haven't checked other areas of the code, but generally super should never be called unless it's from the same method implementation in a subclass.

**Comment by pokeb** [comment]
Hi Nathan

Nice catch, thanks for letting me know. From a quick look I think this only affected ASIHTTPRequest's initWithURL:, this is fixed now.

Thanks again

Ben

**Comment by atnan** [comment]
Thanks Ben! I figured this was quicker than doing the fork/pull request dance.

Cheers,

Nathan
