### ISSUE TITLE
Internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by bradfordcp** [pokeb/asi-http-request#34]
I receive the error "Internal compiler error: Segmentation fault" when attempting to build a project which includes asi-http-request. Pressing build again usually alleviates this error, but it is still quite annoying. This occurs on both my Macbook Pro, Macbook Air, and Mac Pro. Thanks for your help!

**Comment by pokeb** [comment]
Hi Christopher

Yikes, that is strange.

Is this a Mac or iPhone project? Are you able to build the sample projects?

Thanks

Ben

**Comment by bradfordcp** [comment]
iPhone projects, and it happens in two completely different ones. What gets me is that I can simply press build again and it will compile without issues.

Also the compiler doesn't fail on the same file, it varies depending on project.

**Comment by pokeb** [comment]
Hmm. If it's possible to send me a project that demonstrates the issue, I'd be happy to take a look.

b

**Comment by bradfordcp** [comment]
The issue is gone since I updated xCode... maybe it was the version of gcc?

**Comment by pokeb** [comment]
No idea I'm afraid, but I'm glad it seems to be working for you now. I'll close this issue, but please let me know if you encounter this problem again.
