### ISSUE TITLE
Why ASIHTTPRequest releaseBlocks: is empty

### ISSUE THREAD

**Issue by gaosboy** [pokeb/asi-http-request#355]
There is a static method releaseBlocks: called by releaseBlocksOnMainThread, but this method is empty. Why?
And how "Blocks will be released when this method exits" ?

**Comment by jogu** [comment]
The performSelectorOnMainThread call is passed "blocks" as the parameter, so will retain blocks until the given selector (releaseBlocks:) is run and exits - hence the comment in releaseBlocks "Blocks will be released when this method exits".
