### ISSUE TITLE
Stop adding charset header to files in ASIFormDataRequest

### ISSUE THREAD

**Issue by pokeb** [pokeb/asi-http-request#36]
Some servers don't seem to like this, and it's irrelevant for binary data, and misleading for text.

**Comment by pokeb** [comment]
Fixed

**Comment by genericrich** [comment]
What servers don't like it and how can I tell if mine does?

**Comment by pokeb** [comment]
Not sure, but a few people reported this problem. Either way, specifying a charset for binary data should be completely unnecessary.
