### ISSUE TITLE
Is ASIHttpRequest really dead?

### ISSUE THREAD

**Issue by lono175** [pokeb/asi-http-request#368]
Some people say that ASIHttpRequest is no longer maintained. I wonder if it is true or not? 
If it is true, are there any forks which are actively maintained?

**Comment by carsonreinke** [comment]
:skull:

**Comment by jogu** [comment]
It's probably about 50%-ish maintained.

A couple of people (myself included) have write access to the main repository, and will merge in anything that is "obviously" correct or multiple people have confirmed is okay, but that's about it.

Anyone building new apps using ASIHTTPRequest is probably crazy - I can't think of any good reason to do so.

However it does appear that it will work fine on iOS 7 and for the foreseeable future, so there's no need to panic if someone has an existing app that uses ASIHTTPRequest. I've no apps left that use asihttprequest though.

**Comment by lono175** [comment]
That's too bad :( 
Do you know any good alternatives?

**Comment by jogu** [comment]
Raw NSURLConnection is okay these days for many things, but AFNetworking can be the best option.

There's also RESTkit and a few others that are more domain specific.
