### ISSUE TITLE
iPhone download performance.

### ISSUE THREAD

**Issue by peterp** [pokeb/asi-http-request#37]
I don't know if anyone else has experience this but I'm seeing a large performance hit when running the code on an Iphone 3G. (On WiFi.) I got about 30 kbit/s

The same code running on the simulator runs at 200 kbit/s  (My maximum line speed.)

**Comment by pokeb** [comment]
Hi Peter

It is certainly much slower running requests on my iPhone 3G than in the simulator, but I don't think there's an awful lot we can do about this. At a wild guess, it's either down to the speed of the device, the speed of the device's wifi, or the OS passing on network events purposely slowly to keep the battery use down. :)

If you add an NSLog statement to handleBytesAvailable to log the number of bytes received, you'll see that it is called much more often in the simulator than on the device. As far as I can see from profiling in instruments, +[NSURLConnection(NSURLConnectionReallyInternal) _resourceLoadLoop:] is where it is spending its time. In my tests, time spent in ASIHTTPRequest code is negligible (13 samples out of 22900).

If you run the performance tests, you'll see that NSURLConnection is also much slower on the device than in the simulator. Performance for the two seems to be similar in most situations.

On very fast connections, you might be able to eke out a bit more performance by increasing the size of the download buffer (in handleBytesAvailable), but if your line speed is 200kbits, I doubt it would make any difference.

I don't have a 3GS to test on, perhaps requests will run faster there.

As always, I'm open to suggestions, please do reopen this issue or use the google group if you'd like to discuss further.

Best,

Ben

**Comment by peterp** [comment]
Hi Ben,

Thanks. I meant to close this ticket last night - I had read a blog post you made in January about performance and realised that it was simply the device. 

Thanks for the code. It's very much appreciated.
