### ISSUE TITLE
How does it happen? 

### ISSUE THREAD

**Issue by mayujun23** [pokeb/asi-http-request#371]
Everytime,I ran my app,it just stop at the point in asihttprequest.h which declared property named 'username'.

I have debuged it,but I think there is nothing went wrong.

And I use the ASI file in any other project the same way,it worked well.

Here is the code:
- (IBAction)doLogin:(id)sender {
  if (![self queue]) {
      [self setQueue:[[ASINetworkQueue alloc] init]];
      [self queue].maxConcurrentOperationCount = 4;
  }
  ASIFormDataRequest *request = [ASIFormDataRequest requestWithURL: [NSURL URLWithString: @"http://localhost/AppServer"]];
  [request setPostValue:self.usernameInput.text forKey:@"username"];
  [request setPostValue:self.passwordInput.text forKey:@"password"];
  [request setDelegate:self];
  [request setDidFinishSelector:@selector(requestFinished:)];
  [request setDidFailSelector:@selector(requestFailed:)];
  [[self queue] addOperation:request];
  [self.queue go];
  }

**Comment by jogu** [comment]
There's possibly something wrong with self.usernameInput.text.

I don't think this is a bug in ASIHTTPRequest itself.

I suggest following the normal kind of debugging process - start by cleaning out the build folder just in case,  and run the code through the analyser and fix any compiler or analyser warnings - if you still have the issue then enable NSZombies and run through in the debugger. If you're still stuck after that I'd suggest trying to post everything on stackoverflow.com or similar.
