### ISSUE TITLE
Podspec pointing to older commit

### ISSUE THREAD

**Issue by schmittsfn** [pokeb/asi-http-request#386]
Hey there,

Seems like the cocoa pods spec is pointing to an older commit -- it is pointing to the tag 1.8.1, which is based on commit 404bbfe10c3c46824590f2231c4610c2e35f524d.

Here the link: https://github.com/CocoaPods/Specs/blob/master/ASIHTTPRequest/1.8.1/ASIHTTPRequest.podspec

If you wanted I could create a new tag (1.8.2) and add a second pod spec for the never version.

What do you think?

**Comment by jogu** [comment]
I've no objections to you doing so, and I think I'm possibly the only person left with commit access that does anything at all, and even I don't do very much other than merge trivial bug fixes :-)

It would probably be preferable that any podspec mentions that asihttprequest is deprecated and not at all recommended for new projects, and directing people at http://allseeing-i.com/%5Brequest_release%5D; for more info - I'd hate for new users to find it and think that it's something that they should be using!

**Comment by schmittsfn** [comment]
Seems like tags don't get included in pull requests. What I could do is for the podspec to just point to the latest commit id.

I'll also update the pod specs description to include what you mention above and to alert new users that it's kind of deprecated =)

**Comment by jogu** [comment]
ah, yeah, I guess it makes sense that they wouldn't... I can put a tag on I guess.

**Comment by jogu** [comment]
done - tag v1.8.2 now exists

**Comment by schmittsfn** [comment]
awesome, taking care of the rest -- will keep you updated
