### ISSUE TITLE
Crash when incorrect credentials are sent

### ISSUE THREAD

**Issue by zcohan** [pokeb/asi-http-request#4]
I'm setting the credentials with using setUserName and setPassword in the delegate method authenticationNeededForRequest. If credentials are wrong the app crashes.

It looks like the authentication delegate method is being called 3 times before the crash occurs, and from what I understand from the code this shouldn't be happening, and the request should just fail if the authorisation attempt count is 2.

The crash occurs on the line "[self setRequestCredentials:nil];" in ASIHTTPRequest's "attemptToApplyCredentials".

I have an example app if necessary.

**Comment by pokeb** [comment]
Ignore 'authenticationRetryCount', it is only used for handling NTLM authentication. I don't think there's any limit on the number of times authenticationNeededForRequest can be called, assuming the wrong credentials are supplied each time.

A sample project would be really helpful => ben@allseeing-i.com.

Thanks!

Ben

**Comment by pokeb** [comment]
Closing - seems to be fixed now.
