### ISSUE TITLE
warnings during compilation

### ISSUE THREAD

**Issue by mackuba** [pokeb/asi-http-request#40]
When I compile my application which uses ASIHTTPRequest, I get two warnings with such message:

```
incompatible Objective-C types assigning 'struct NSDictionary *', expected 'struct NSMutableDictionary *'
```

Both are reported in ASIHTTPRequest.m, one on @synthesize proxyCredentials and the other on @synthesize requestCredentials. It's not really a problem, but it is a bit annoying to see this every time I recompile the app ;)

**Comment by pokeb** [comment]
Hi Jakub

Thanks for letting me know, I should certainly get this changed.

Do you have a particular build setup that triggers this warning? Are you building for Mac or iPhone? I've been experimenting with different settings, and I can't seem to reproduce. If so, it will be helpful if I can turn on the flag you've used. :)

Thanks

Ben

**Comment by mackuba** [comment]
Ok, I've found it - it only happens when you set garbage collector to 'required' (I need this because it's a MacRuby application).

**Comment by pokeb** [comment]
Fix warnings that appear when garbage collection is on - Closed by 389a764d62a8765a2390449e6048b9e31bcda200

**Comment by pokeb** [comment]
Thanks again for letting me know, should be fixed now.

Best

Ben

**Comment by mackuba** [comment]
Warnings disappeared, thanks! (Though I've just opened another bug about memory leaks: http://github.com/pokeb/asi-http-request/issues/issue/45 :)
