### ISSUE TITLE
iPhone Sample QueueViewController Image loading works on Simulator but not on Device

### ISSUE THREAD

**Issue by varrogy** [pokeb/asi-http-request#41]
Hi!

I've noticed a bug in the sample project.
When I build the sample project and run on the Simulator everything is in order, all URL request works. But when I try to run this project on an iPhone I noticed when try to run the Queue sample (2. tab) it never finish the downloading and never show any images!

I found a workaround, read below:

QueueViewController.m (iPhone.xcode)
- (IBAction)fetchThreeImages:(id)sender
  {
  .
  .
  .
  ASIHTTPRequest *request;
  request = [ASIHTTPRequest requestWithURL:[NSURL URLWithString:@"http://allseeing-i.com/ASIHTTPRequest/tests/images/small-image.jpg"]];
  [request setDownloadDestinationPath:[[[[NSBundle mainBundle] bundlePath] stringByDeletingLastPathComponent] stringByAppendingPathComponent:@"1.png"]];
  [networkQueue addOperation:request];

In this section the download destination path points to the Application's root directory which is writeable on the Simulator but not on Device (the device throws a write deny message, but this message only shows in the device log only not in the debugger console). So I changed the download destination to CachedImages below the NSCachesDirectory which is writeable on the Device

Regards,

**Comment by pokeb** [comment]
I think this was fixed a while back, see:

http://github.com/pokeb/asi-http-request/commit/9312f4570d26e1b06265931938572d1c0aaf2f6e

Best,

Ben
