### ISSUE TITLE
Need to import UIKit in certain files to help with building static libs

### ISSUE THREAD

**Issue by pokeb** [pokeb/asi-http-request#43]
http://groups.google.com/group/asihttprequest/browse_thread/thread/a255ba0c63aec5ad

**Comment by pokeb** [comment]
Not sure if this is still an issue, must get around to testing.

**Comment by dalewking** [comment]
Why is this still not fixed?!?

**Comment by dalewking** [comment]
Sorry, wrong problem

**Comment by pokeb** [comment]
Ok, ASIHTTPRequest.h imports UIKit now when targeting iOS 4+. This fixes the problem of static libs failing to build because background task support needs UIKit.
