### ISSUE TITLE
iOS4 - problems with authentificaiton dialog

### ISSUE THREAD

**Issue by ghost** [pokeb/asi-http-request#44]
In iOS 4, the authentication dialog does not seem to work, its shown as expected, but it isn't possible to write a username or password into it.
The keyboard appears, it is possible to select a textfield aswell, but the input doesn't seem to reach the textField.

**Comment by pokeb** [comment]
The authentication dialog has been updated for iOS4 and iPad in v1.7, do let me know if you encounter problems.

Best

Ben
