### ISSUE TITLE
memory leaks with garbage collection

### ISSUE THREAD

**Issue by mackuba** [pokeb/asi-http-request#45]
If I run 'build and analyze' on a garbage-collection-enabled project using ASIHTTPRequest, I get 10 warnings with the message "Potential leak (when using garbage collection) of an object..." (in ASIFormDataRequest.m and ASIHTTPRequest.m). Could you look into this? (It seems it's mostly related to objects allocated using CoreFoundation functions and deallocated using autorelease.)

**Comment by pokeb** [comment]
I don't have any experience with GC - does this mean these will actually leak, or do you think Clang is just confused?

I guess in some cases I could switch to using CFRelease(), but I prefer to use autorelease. Lots of methods return early, so it's easier to ensure I'm not forgetting to release something.

**Comment by mackuba** [comment]
I don't have any experience with CoreFoundation, but it looks like this actually does cause memory leaks. (I'm thinking now that those reports by my app's users that it leaks like hell might have something to do with this... though I haven't investigated this at all so I'm just guessing here :)

There's a page in Apple's documentation that explains in detail how to use CoreFoundation with garbage collection: http://developer.apple.com/mac/library/documentation/cocoa/conceptual/GarbageCollection/Articles/gcCoreFoundation.html

It seems the solution is to call CFMakeCollectable or NSMakeCollectable on the CoreFoundation objects - if I understand correctly, in GC mode this lowers the reference count for CF objects to zero (making the object collectable when it goes out of scope, not releasing it immediately), and in non-GC mode it does nothing, so it's safe to use it even without GC. If I wrap a call to e.g. CFReadStreamCopyProperty in CFMakeCollectable, Clang stops complaining.

The leak is apparently caused by the fact that CF\* creation methods increase the reference count even in GC mode, but Cocoa's [release] and [autorelease] are no-ops in GC mode so they don't lower it and it stays above 0.

**Comment by mackuba** [comment]
I've looked at the memory allocation in my app and I'd say that probably the problem is somewhere within the UI (mainly with images), not with the http requests... but it would be nice to fix this anyway.

**Comment by pokeb** [comment]
Many thanks for the info! :)

I've wrapped all the calls the static analyser complains about in NSMakeCollectable, and added CFMakeCollectable calls in markAsFinished to free up the CF objects a request hangs on to (as dealloc won't be called). I've done a quick run with the leaks instrument, and it looks like the leaks should be gone, but please let me know if you're still seeing them!

Thanks again

Ben

**Comment by mackuba** [comment]
Looks good, no more warnings, thanks :)

**Comment by MrZoidberg** [comment]
Guys, does this issue fixes problems for iOS or it is Mac only?

**Comment by mackuba** [comment]
Definitely Mac only, this is only relevant to garbage collection and there's no garbage collection on iOS for now.
