### ISSUE TITLE
KVO notifications badly ordered in markAsFinished

### ISSUE THREAD

**Issue by ghost** [pokeb/asi-http-request#48]
```
- (void)markAsFinished
 {
    [self willChangeValueForKey:@"isFinished"];
    [self didChangeValueForKey:@"isFinished"];
    [self setInProgress:NO];
    CFRunLoopStop(CFRunLoopGetCurrent());
}
```

should be 

```
- (void)markAsFinished
{
    [self willChangeValueForKey:@"isFinished"];
    [self setInProgress:NO];
    [self didChangeValueForKey:@"isFinished"];
    CFRunLoopStop(CFRunLoopGetCurrent());
}
```

I'm seeing a EXC_BAD_ACCESS when I run through this code. I'm not aware that this defect would cause that though.

**Comment by pokeb** [comment]
Hi sockettrousers (love the name)!

I have had another report of a crash relating to this method, I think it's quite likely that this is the cause of a crash.

The other suggested fix was to wrap the whole thing in a retain, but this seems more elegant, will merge this fix today.

Best

Ben

**Comment by ghost** [comment]
Sadly it's not a fix, the trailing didChangeValue still generates the exception. I think maybe 
    [[self retain] autorelease];
at the beginning of the function is the fix. I imaging that the request is being removed from the queue and deallocated as soon as isFinished changes. My fix above is the 'right thing' for KVO.

**Comment by pokeb** [comment]
Ok, thanks for the heads up. I think retain + release is probably better for clarity, I'll do that.

**Comment by ghost** [comment]
The advantage of `[[self retain] autorelease];` is that you're guaranteed it is always released outside your context.

**Comment by pokeb** [comment]
Ok, maybe you're right. It looks like a HEAD request could potentially cause a crash with the manual release anyway, as it needs to mark its parent as finished too.
