### ISSUE TITLE
iOS 4 issue in 1.6.2 release: addTimeInterval deprecated

### ISSUE THREAD

**Issue by dirkdk** [pokeb/asi-http-request#53]
hi there,

the last official release of ASIHttpRequest gives a warning when compiling against iOS 4:

line 3527 in ASIHttpRequest.m:
throttleWakeUpTime = [[bandwidthMeasurementDate addTimeInterval:extraSleepyTime] retain];

the method addTimeInterval is deprecated. Changing it to dateByAddingTimeInterval seems to fix it.

keep up the good work, love ASIHttpRequest!

dirk

**Comment by pokeb** [comment]
Hi Dirk

I've replaced the call with initWithTimeInterval:sinceDate:, which should work on all OS versions.

Best

Ben

**Comment by dirkdk** [comment]
thanks!
