### ISSUE TITLE
Task completion support

### ISSUE THREAD

**Issue by pokeb** [pokeb/asi-http-request#56]
Add an easy way to mark requests or queues as background tasks for iOS 4, so they can continue running when the app is exited.

Requested here:

http://groups.google.com/group/asihttprequest/browse_thread/thread/fc10986a6569a35a

**Comment by pokeb** [comment]
Initial implementation here, seems to work ok:
http://github.com/pokeb/asi-http-request/tree/backgroundtask

Will be in master for v1.8

**Comment by lukeredpath** [comment]
I've been trying this out as a patch applied to 1.7. It works fine on iOS4 but will cause a crash if you are deploying to older devices. The conditional is fine for compile-time checking (it won't compile if you are compiling with an older base SDK) but runtime checks are still required when building with the latest SDK but an older deployment target.

Here's a patch:
http://gist.github.com/546082

**Comment by pokeb** [comment]
Thanks Luke - I've merged your patch now. :)

**Comment by pokeb** [comment]
Background task support is in master now.
