### ISSUE TITLE
ASIHTTPRequest fails when connecting through a socks proxy (from PAC file)

### ISSUE THREAD

**Issue by sylverb** [pokeb/asi-http-request#59]
Hello,
On my iPhone, I have a pac file configuring a socks proxy :
    function FindProxyForURL(url, host) {
        return "SOCKS 192.168.1.1:20000";
    }
ASIHTTPRequest fails as it's trying to use 192.168.1.1:20000 as a HTTP Proxy ...

the following lines in - startRequest method (where it setup HTTP Proxy) solve the problem :

```
    hostKey = (NSString *)kCFStreamPropertySOCKSProxyHost;
    portKey = (NSString *)kCFStreamPropertySOCKSProxyPort;
    NSMutableDictionary *proxyToUse = [NSMutableDictionary dictionaryWithObjectsAndKeys:[self proxyHost],hostKey,[NSNumber numberWithInt:[self proxyPort]],portKey,nil];
    CFReadStreamSetProperty((CFReadStreamRef)[self readStream], kCFStreamPropertySOCKSProxy, proxyToUse);
```

I'll just have to make this dynamically detecting proxy type ...

Sylver

**Comment by sylverb** [comment]
Ok, here is my solution (feel free to adapt it ...) :
create a proxyType property (NSString),
fill it with the proxy settings dictionary :
    [self setProxyType:[settings objectForKey:(NSString *)kCFProxyTypeKey]];
then when applying proxy settings, make several cases :
    if ([[self proxyType] isEqualToString:(NSString *)kCFProxyTypeHTTP]) {
        ...
    } else if ([[self proxyType] isEqualToString:(NSString *)kCFProxyTypeHTTPS]) {
        ...
    } else if ([[self proxyType] isEqualToString:(NSString *)kCFProxyTypeSOCKS]) {
        ...
    }
Maybe a better solution would be to create an enum with proxy types and to use these values for tests ... I let you check what's the best implementation in your opinion ;)

Sylver

**Comment by pokeb** [comment]
Hi Sylver

Thanks very much for letting me know.

I added the proxyType property, and was able to get it working with a simple SOCKS proxy I setup using SSH, and with the proxy server in a PAC specified in system prefs (on Mac). Can you let me know if it's working for you?

I guess it could use an enum for proxy type, but setting proxy settings manually is something I suspect very few users will ever do.

ASIHTTPRequest doesn't currently handle kCFProxyTypeHTTPS, though HTTPS via a regular kCFProxyTypeHTTP proxy should work fine. 

Thanks again

Ben

**Comment by sylverb** [comment]
Just updated to latest version (v1.7-6) and it's working great with my SOCKS proxy !
I was not aware of all these proxies stuff in ASIHTTPRequest until I met a problem today ;)
Thanks for your great work ;)

Sylver
