### ISSUE TITLE
Docs refer to "request:didReceiveResponse:" rather than "request:didReceiveData:"

### ISSUE THREAD

**Issue by atnan** [pokeb/asi-http-request#60]
The documentation (http://allseeing-i.com/ASIHTTPRequest/How-to-use) under "Handling the response data as it arrives" refers to "request:didReceiveResponse:" rather than "request:didReceiveData:".

Not a huge problem by any measure :-)

**Comment by pokeb** [comment]
Thanks for the heads up, should be fixed now.
