### ISSUE TITLE
Check response header "Content-Range" to see whether the requested byte range is returned

### ISSUE THREAD

**Issue by martijnthe** [pokeb/asi-http-request#63]
It would be a good idea to check the response headers for "Content-Range" to see whether the requested byte range is returned, if the headers don't contain the header, it should discard the previously downloaded bytes and start over again.

**Comment by pokeb** [comment]
Dump partial download when no Content-Range header supplied (closed by 4f76c895eed601ad37f31147594a5605ad10f3e4)
Tweaks to fix more LLVM warnings
