### ISSUE TITLE
Synchronous.nib missing for iPad example

### ISSUE THREAD

**Issue by epreston** [pokeb/asi-http-request#67]
Summary: The Synchronous.nib is missing from the current iOS sample application in the master branch.  The iPadMainWindow.xib references a this nib file for the detail display of the split view controller.

Notes: iPad example might be a work in progress, not implemented.

Impact: Application crashes, fails to launch when built for iPad. Dependent resource file missing.

Steps to reproduce:  Open iPhone sample project in xcode, open iPadMainWindow.xib in interface builder, use the inspector to view the attributes of the "Synchronous View Controller" used in the detail display of the split view.

User perception: fear and self-lauthing.

**Comment by pokeb** [comment]
Thanks for your report!

I think Synchronous.nib is one of the nib files used by the old sample project - it shouldn't be needed anymore. I'm surprised it is causing the iPad sample to crash for you - I am able to build and run the iPad sample without it.

Either way, I guess the reference to it needs to be removed - will try to get this changed in the next couple of days.

Thanks again

Ben

**Comment by pokeb** [comment]
Fix nib name in iPad sample (closed by b60d4f2f2dec7c47fcb76d8975d69c1f1f714449)
