### ISSUE TITLE
ASIHTTPRequest calling [self init] in -initWithURL:

### ISSUE THREAD

**Issue by atticus** [pokeb/asi-http-request#68]
Is there a reason that -initWithURL: is calling [self init] rather than [super init]?  I'm subclassing ASIHTTPRequest, and if I override -init I get an endless loop when initWithURL: calls [self init].  If I modify the line to "self = [super init];" it works fine.  My initializer:
- (id)initWithType:(JLHTTPRequestType)requestType {
  if ((self = [super initWithURL:nil])) {
      // [self setURL:....] based on requestType
  }
  return self;
  }

The issue may actually be that while -initWithURL: seems to be the designated initializer at first glance, -init actually is.  That works fine, except that calling -init directly means I lose the common defaults that are set in -initWithURL:. I could copy all of them into my own initializer, but I'd have to remember to check them against all future updates to ASIHTTPRequest in case something important was added or changed.  Pulling those values out into their own config method would allow any custom initializer to keep up to date with whatever you choose to include there, not just -initWithURL:, but perhaps I'm worrying too much about keeping in sync with those defaults.

Thanks,
Atticus

(ASIHTTPRequest.m - line 258)

**Comment by atnan** [comment]
You should always call self if the method you're currently in (initWithURL:) does not match the method you're calling (init). If ASIHTTPRequest called [super init] in -initWithURL:, subclasses of ASIHTTPRequest could not override -init.

For the same reason, your -initWithType: implementation should be calling [self initWithURL:].

Here's a worked example:

http://gist.github.com/513571

Cheers,

Nathan

**Comment by pokeb** [comment]
Will close
