### ISSUE TITLE
ASIDownloadCache + NSOperationQueue + ASIReloadIfDifferentCachePolicy Issue

### ISSUE THREAD

**Issue by jasconius** [pokeb/asi-http-request#71]
I've come across what I feel is a bug, where if you set an individual request to ASIReloadIfDifferentCachePolicy and add it to an Operation Queue, the Request Complete handler by the Operation Queue twice. It appears that it is called once by what appears to be a proxy object created in the cache method in ASIHTTPRequest.m, and once by the network event.

What I think is happening is that the act of accessing the remote file triggers the network event, which calls the requestFinished method in addition to the cache method... so you end up with 6 requests in an OperationQueue firing the Request Finished event 12 times total.

I could sort of understand why it might be useful to know when the request is done checking if the version on the web is different, but at the very least I should be able to distinguish between them at that point so I can discard the ones I don't need for a given purpose.

**Comment by pokeb** [comment]
Hi

Many thanks for the bug report! It shouldn't be called twice, I'm not quite sure how I missed this one... :)

I think this should be fixed now, see:

http://github.com/pokeb/asi-http-request/commit/8998d7a048b7042bd9853b2e78716d70440743a8

Best,

Ben
