### ISSUE TITLE
which method can i use to request HTTP body?

### ISSUE THREAD

**Issue by bxl** [pokeb/asi-http-request#73]
excuse me.i' m a fresh.i want to login a netsite,such as www.renren.com.i get the request headers and request body of HTTP by fiddler,but i don't know which method i can use.thank you for your reply!

**Comment by pokeb** [comment]
I'm afraid this is not really the correct place to answer your question.

For help with ASIHTTPRequest, please post a message to the google group at http://groups.google.com/group/asihttprequest.

Best,

Ben
