### ISSUE TITLE
ASINetworkQueue seems to be losing the delegate?

### ISSUE THREAD

**Issue by dredful** [pokeb/asi-http-request#77]
I have verified that the delegate is initially set when ASINetworkQueue is called. However the following method keeps crashing:

```
    - (void)requestFinished:(ASIHTTPRequest *)request
```

on this line:

```
[[self delegate] performSelector:[self requestDidFinishSelector] withObject:request];
```

With an error of:

```
Program received signal:  “EXC_BAD_ACCESS”.
```

I have determined that the “EXC_BAD_ACCESS” is because [self delegate] is no longer valid. The last place I can verify the [self delegate] is in: ASINetworkQueue's - (void)requestStarted:(ASIHTTPRequest *)request

I can see that it is missing as early as:

```
- (void)requestReceivedResponseHeaders:(ASIHTTPRequest *)request
```

Is there something that I could be doing to cause this issue? Is anyone else seeing or has seen this problem?

Thanks.

**Comment by dredful** [comment]
Please Ignore. The problem was outside of asi-http-request.

**Comment by eliavm** [comment]
What was the problem? I am facing the same problem....

**Comment by Rich86man** [comment]
I had this same issue. The problem ended up being on my end as well. I started a request, set my viewController as the delegate, the vc disappeared and when the response came back my delegate was gone and app crashed

**Comment by zumbrun** [comment]
Thank you!!  I had this problem and am so grateful to Rich86man for the post.  Laura
