### ISSUE TITLE
how to get the object of a bucket ?

### ISSUE THREAD

**Issue by sleuth007** [pokeb/asi-http-request#78]
Hi, I am not able to get the object from the bucket. I am using Walrus S3.
The response data which I receive is :  Failure:403 forbidden
Please tell me the correct way of getting objects in objective c

**Comment by pokeb** [comment]
Hi

Please post a message to the google group at http://groups.google.com/group/asihttprequest with the code you are using to fetch the object, and I'll be happy to help if I can.

Thanks

Ben
