### ISSUE TITLE
RequestDidFinishSelector called twice for cached response

### ISSUE THREAD

**Issue by pthompson** [pokeb/asi-http-request#79]
I am seeing that my RequestDidFinishSelector is being called twice when I receive a "304 Not Modified" response from the server. I am using the default sharedCache.

Is this a bug?

Can I work around the problem by always ignoring repeated responses? That is, can I assume that the RequestDidFinishSelector is (or should be) only called once per request?

-Patrick

**Comment by pokeb** [comment]
This sounds like a bug that was fixed a few weeks ago (http://github.com/pokeb/asi-http-request/issues/closed/#issue/71)

If you update to the latest version of ASIHTTPRequest, are you still seeing this issue?

Best,

Ben

**Comment by pthompson** [comment]
That fixed the issue. Thanks!

-Patrick
