### ISSUE TITLE
Setting request encodings is not possible

### ISSUE THREAD

**Issue by jorfermo** [pokeb/asi-http-request#8]
We were discussing it in this post of the group:

http://groups.google.com/group/asihttprequest/browse_thread/thread/1aad7e268ed1444e

It would be interesting that we could set the character encoding of the form requests

Thank you

**Comment by pokeb** [comment]
This sounds like a great idea, thanks!

Will get something sorted once I've had a chance to catch up on the google group discussions.

Best!

Ben

**Comment by jorfermo** [comment]
Ok thank you.

Feel free to contact me to make any test if needed.

Regards.

**Comment by pokeb** [comment]
Ok, have added stringEncoding property to ASIFormDataRequest. Please give it a try and let me know how you get on.

**Comment by pokeb** [comment]
I'm going to close this ticket now, please open a new ticket it you find problems.

Best

Ben
