### ISSUE TITLE
Potential Leak in ASIHTTPRequest.m

### ISSUE THREAD

**Issue by clementkasual** [pokeb/asi-http-request#85]
- (void)runRequests
  {
  // Should keep the runloop from exiting
  CFRunLoopSourceContext context = {0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};
  CFRunLoopSourceRef source = CFRunLoopSourceCreate(kCFAllocatorDefault, 0, &context);
  CFRunLoopAddSource(CFRunLoopGetCurrent(), source, kCFRunLoopDefaultMode);
  
  while (1) {
      NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
      CFRunLoopRun();
      [pool release];
  }
  
  // Should never be called, but anyway
  CFRunLoopRemoveSource(CFRunLoopGetCurrent(), source, kCFRunLoopDefaultMode);
  CFRelease(source);
  }

It doesn't like while(1).

**Comment by pokeb** [comment]
Closing because this was changed ages ago to use a local variable, IIRC to workaround the clang warning.
