### ISSUE TITLE
-[ASIDownloadCache _CFURLCache]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by kevinelliott** [pokeb/asi-http-request#86]
**\* -[ASIDownloadCache _CFURLCache]: unrecognized selector sent to instance 0x5d27250
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[ASIDownloadCache _CFURLCache]: unrecognized selector sent to instance 0x5d27250'

This error started showing up when I updated to 1.8-merged today.

**Comment by pokeb** [comment]
Hi Kevin

Hmm, not sure. Are you trying to use ASIDownloadCache as an NSURLCache? If so, I'm afraid I removed this feature because it didn't work properly.

Best,

Ben

**Comment by kevinelliott** [comment]
Oh shucks, that's exactly what I wanted. I need requests made to be retrievable by UIWebView!

**Comment by kevinelliott** [comment]
Which of course they were previously. Do you have any ideas how I might be able to do this another way?

(I still need to get ASIWebPageRequest working too, also with the shared cache with UIWebView)

**Comment by pokeb** [comment]
My apologies, after a lot of banging my head against the wall, I basically came to the conclusion that NSURLCache is impossible to subclass in any meaningful way.

If you come at the problem from another direction, there may be a way to accomplish what you need. Specifically, look at ASIReplaceExternalResourcesWithLocalURLs, which lets you create offline copies of stuff with external resources saved in separate files. With judicious use of the baseURL, you can get UIWebView to load in content directly from your ASIDownloadCache. (See the iPad sample project for an example).

I will close this issue, but please do post to the google group if you'd like to discuss further :)

Best,

Ben
