### ISSUE TITLE
originalURL is null when request didUseCachedResponse ==YES

### ISSUE THREAD

**Issue by dhiraj** [pokeb/asi-http-request#87]
Instead of null, should it not be the same as the normal URL parameter even on cached results? I'm having to put if conditions all over the place, just to check if it was a successful cache hit or not, since I am using the requested URL as key in my UIImage caching Dictionary.

**Comment by pokeb** [comment]
I think this should be fixed in this commit:

https://github.com/pokeb/asi-http-request/commit/791de35be7f3964d3f8b310c40a972002206df4f

Many thanks!

Ben
