### ISSUE TITLE
ASICacheDelegate bypassed when restoring from cache

### ISSUE THREAD

**Issue by jfmorin** [pokeb/asi-http-request#88]
ASIHTTPRequest bypass the ASICacheDelegate protocol and directly read cached data from disk.

In "- (BOOL)useDataFromCache" we can fin the following line:
[theRequest setRawResponseData:[NSMutableData dataWithContentsOfFile:dataPath]];

I would rather expect something like:
[theRequest setRawResponseData:[NSMutableData dataWithData:[[self downloadCache] cachedResponseDataForRequest:self]]];

Reading directly from the disk prevent implementation of custom cache that are not on disk.

**Comment by pokeb** [comment]
This is in v1.8, many thanks for letting me know!

Best,

Ben
