### ISSUE TITLE
No Progress for ASIS3Request's queued in ASINetworkQueue

### ISSUE THREAD

**Issue by leviathan** [pokeb/asi-http-request#9]
I've setup multiple ASIS3Request's and added them to a ASINetworkQueue.
The S3 Requests have a download and temporary download path, resume download is allowed.

I've setup a UIProgressView as downloadProgressDelegate for the queue.

However it seems that the progress is not updated.
I've debugged the methods:
- (void)incrementDownloadSizeBy:(unsigned long long)bytes
  and 
- (void)incrementDownloadProgressBy:(unsigned long long)bytes
  in the ASINetworkQueue class and both times the "bytes" value passed to these methods is 0.

Any ideas how to solve this?

**Comment by pokeb** [comment]
Hi

Have you set showAccurateProgress to YES on the queue?

Thanks

Ben

**Comment by leviathan** [comment]
Yes I did that.
[self setNetworkQueue:[ASINetworkQueue queue]]; 
[[self networkQueue] setShowAccurateProgress:YES];

I've debugged the ASIHTTPRequest class. In the method
- (void)updateDownloadProgress it seems that the "responseHeaders" is empty, because the "if" always fails.
  // We won't update download progress until we've examined the headers, since we might need to authenticate 
  if (responseHeaders) {
  .....

**Comment by pokeb** [comment]
If the response headers are empty, it's unlikely to be downloading any data at all.

Did you start the queue ([[self networkQueue] go]?) If so, are you getting an error in your requestDidFailSelector delegate method?

**Comment by leviathan** [comment]
Well the data is downloaded.

I've setup the delegate methods like you recommended in the gist http://gist.github.com/150447:
[[self networkQueue] setRequestDidFinishSelector:@selector(requestFinished:)];
[[self networkQueue] setRequestDidFailSelector:@selector(requestFailed:)];
[[self networkQueue] setQueueDidFinishSelector:@selector(queueFinished:)];

However none of the delegate methods is called (I've added log messages).
Not even the "queueFinished" delegate method. Although the data is downloaded successfully.

**Comment by pokeb** [comment]
Ok. Can you mail me your code, (ben@allseeing-i.com) and I'll take a look?

Thanks

Ben

**Comment by leviathan** [comment]
Source can be found here: http://gist.github.com/214556

**Comment by leviathan** [comment]
If I do set the UIProgressView Delegate directly for each s3Request it works.

// [s3Request setDownloadProgressDelegate:[dc progress]];

However this causes the progress bar to flicker, because each s3Request reports its own
progress. It seems that the ASIS3Request is capable of reporting progress. But the queue
seems to be unable to query and summarize the request's progress.

**Comment by pokeb** [comment]
Ok, I think I see the problem. It will work when accurate progress is off, but not when it is turned on. ASIS3Requests don't have their HEAD request built properly when using an ASINetworkQueue. Will try to fix this morning.

**Comment by pokeb** [comment]
Refactor ASIHTTPRequest, ASIS3Request to allow HEAD requests created by ASINetworkQueues to override headers on their main request
This should fix accurate progress tracking for ASINetworkQueues containing ASIS3Requests
Added progress test for ASIS3Request
Hopefully closed by 47b4e2cc35e094799db094a74ed6d4e8dc9a5e7e

**Comment by pokeb** [comment]
Ok, this was a bit more tricky to fix than I thought... can you try with the latest version and let me know if it seems to be working now?

**Comment by leviathan** [comment]
Perfect! 
Works like a charm! 
Thanks!
