### ISSUE TITLE
CRASH *** -[ASIHTTPRequest performThrottling]: message sent to deallocated instance 0x9aca00

### ISSUE THREAD

**Issue by steipete** [pokeb/asi-http-request#90]
**\* -[ASIHTTPRequest performThrottling]: message sent to deallocated instance 0x9aca00

see screenshot
http://skitch.com/steipetee/d9cax/system

i'm using v1.8/latest  2ff7b0cded41f97c5076

just used ASIHTTPRequest (with blocks), did nothing special...

**Comment by steipete** [comment]
this is much more critical than the blocks issue (which i solved with removing string references to the view in the block)

but this bug keeps going... and i really don't want to go back to 1.7 and rewrite all requests w/o blocks.

can i somehow help you finding that one?

**Comment by steipete** [comment]
it happens after using the app a while, making subsequent ASIHTTPRequests (that use blocks)

if i step into and try to print self, i get

Printing description of self:
2010-11-10 14:14:55.795 MyApp[2435:6003] **\* -[ASIHTTPRequest _cfTypeID]: message sent to deallocated instance 0x927e00

**Comment by pokeb** [comment]
Hi Peter

The screenshot doesn't seem to be working for me at the moment. If it's possible to send me something I can use to reproduce, that would be great, but I'll do some testing myself today.

Best

Ben

**Comment by steipete** [comment]
skitch seems to have problem currently, i'll uploaded another one: http://d.pr/P04P
the bug doesnt not occur in simulator.

**Comment by pokeb** [comment]
Does this change make any difference?

https://github.com/pokeb/asi-http-request/commit/a5af299396cb2bd174d5d3658776206452832b8e

**Comment by steipete** [comment]
no, same error :(

i'm trying to see which request it was, but can't get MallocStackLoggingNoCompact to work.

**Comment by pokeb** [comment]
Argh, I'm being an idiot.

If you add CFRetain(self) at the start of handleNetworkEvent, just before the switch statement, and CFRelease(self) at the end of the method, I imagine this will fix the problem, but please let me know.

**Comment by steipete** [comment]
Yes, that's the fix! Thanks so much!

So somewhere in the function the own object gets deallocated?

Can you check that in or should I send a pull request?

**Comment by pokeb** [comment]
I foolishly took this out earlier on as part of some fixes for garbage collected builds (IIRC it was using [[self retain] autorelease], which wouldn't have worked properly in a GC build).

I'll add this in a sec.

Thanks again for all your help with this!

Ben

**Comment by steipete** [comment]
you can't imagine how happy I am that this issue is fixed... would been such a PITA to backport to 1.7... blocks ftw!
