### ISSUE TITLE
some Warnings

### ISSUE THREAD

**Issue by florianbachmann** [pokeb/asi-http-request#97]
Hi could you resolve these warnings? So i have a warning free project :-)
Thanks in advance :-)
ASIDownloadCache.m:356:0 Suggest parentheses around && within ||
ASIHTTPRequest.m:431:0 Undeclared selector 'releaseBlocks:'
ASIHTTPRequest.m:1752:0 Undeclared selector 'callBlock:'
ASIHTTPRequest.m:1784:0 Undeclared selector 'performInvocation:onTarget:releasingObject:'
ASIHTTPRequest.m:2497:0 Undeclared selector 'askDelegateForProxyCredentials'
ASIHTTPRequest.m:2544:0 Undeclared selector 'askDelegateForCredentials'
ASIHTTPRequest.m:3436:0 Undeclared selector 'hideNetworkActivityIndicatorAfterDelay'
ASIHTTPRequest.m:4215:0 Undeclared selector 'hideNetworkActivityIndicatorIfNeeeded'
ASIHTTPRequest.m:4240:0 Undeclared selector 'runRequests'

**Comment by florianbachmann** [comment]
so you just need to add this: :-)

<pre><code>
@interface ASIHTTPRequest ()
//...
+ (void)releaseBlocks:(NSArray *)blocks;
- (void)callBlock:(ASIBasicBlock)block;
+ (void)performInvocation:(NSInvocation *)invocation onTarget:(id *)target releasingObject:(id)objectToRelease;
- (void)askDelegateForProxyCredentials;
+ (void)hideNetworkActivityIndicatorAfterDelay;
+ (void)hideNetworkActivityIndicatorIfNeeeded;
+ (void)runRequests;
- (void)askDelegateForCredentials;
//...
</code></pre>

**Comment by pokeb** [comment]
Hi Flori

I think I've fixed all the undeclared selector warnings, but please let me know if you're still seeing issues.

Best

Ben

**Comment by florianbachmann** [comment]
thanks :-)

just one more,
the compiler tells me:
ASIDownloadCache.m:356:0 Suggest parentheses around && within ||

and in this Line you write something like

<pre>
<code>
if (exists && !isDirectory || !exists) {
    [[self accessLock] unlock];
    return;
}
</code>
</pre>


which I don't understand
if exists is true AND someother thing OR exists is false?

i hope you can clearify it :-)
regards 
Flori

**Comment by pokeb** [comment]
Fix suggest parentheses issue
closed by ecf90598c78a120d74af56529485676efd28c45d
